### ISSUE TITLE
Should 'Short Link' perserve basemap choice?

### ISSUE THREAD

**Issue by oeon** [openstreetmap/openstreetmap-website#468] opened 2013-08-30 16:33 UTC
Short Link(s) currently do not preserve basemap choice, e.g. MapQuest selected, Short Link clicked but resolves to default OSM basemap.

**Comment by AntonKhorev** [comment] 2024-05-01 12:18
duplicate of #703, already fixed

**Closed** 2024-05-01 14:36 UTC
