### ISSUE TITLE
2 menus overlap from 840px to 910px width viewport

### ISSUE THREAD

**Issue by bezdna** [openstreetmap/openstreetmap-website#2536] opened 2020-02-13 16:25 UTC
![image](https://user-images.githubusercontent.com/518939/74455391-e8202f00-4e8d-11ea-8e8c-072cdcd9f1dc.png)
not always reproduced

**Comment by HolgerJeromin** [comment] 2020-02-14 07:21
Probably depending on the language, too.

**Comment by gravitystorm** [comment] 2020-02-14 07:28
> Probably depending on the language, too.

No, there's javascript that hides the secondary menu based on the actual width, so it already takes into account different label lengths (and different numbers of items, e.g. if a moderator has the additional Issues link). I think the problem here is that it's a finickity bug, since it works fine most of the time.

You can test it out using the "Responsive Design Mode" in firefox, for example, where it's easy to adjust the width of the screen.

**Comment by gravitystorm** [comment] 2023-08-02 10:48
@bezdna I've been working on related things for a while, and not managed to reproduce this. Do you have any suggestions?

If we can't reproduce then unfortunately I'll need to close this issue.

The most likely thing would be if there's something preventing the javascript code from completing (the part that decides to hide the menu, that is), so if you can get it to happen only sometimes, then the JS console might provide some clues.

**Comment by AntonKhorev** [comment] 2023-08-02 17:16
1. Set set screen width to something really narrow, like 200px
2. Reload the page
3. Gradually make screen wider

**Comment by gravitystorm** [comment] 2023-08-02 17:32
Thanks! I can reproduce that now. 

I suspect that "really narrow" is "narrower than the expanded version of the secondary menu" and something is going wrong there when trying to calculate its width.

**Comment by AntonKhorev** [comment] 2023-10-17 11:16
"Really narrow" seems to be "causing line breaks inside rendered buttons and menu items" in which case their calculated width is incorrect once the window gets wider and breaks disappear.

**Closed** 2023-11-22 17:22 UTC
Labels: bug, ui
