### ISSUE TITLE
IP Rights in the OSM XML format

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#2552] opened 2020-03-06 07:14 UTC
@SteveC @zerebubuth @gravitystorm @systemed @ssm1 @avar @IgnoredAmbience  @stefanb @John07 @crschmidt @woodpeck the LWG has been asked about the situation with respect to ownership of intellectual property rights in the 0.5 / 0.6 version of the OSM XML document definition. 

I suspect this may have been prompted by [Google v. Oracle America](https://en.wikipedia.org/wiki/Google_v._Oracle_America). As there is no formal written definition that I know of, but then what do I know, I don't quite see how there can be separate creative rights in something that was never expressed outside of the actual code, but just to be sure I'm checking here so that any of you have the opportunity to raise your hand and claim authorship.

In the absence of any feedback to the contrary I'll be conveying something appropriately hand wavy to the inquirer.

**Comment by systemed** [comment] 2020-03-06 10:35
I have a faint recollection that @SteveC and @zerebubuth expressly disclaimed any rights to it in a mailing list posting many (10+) years ago, but can't find that on a quick search.

**Comment by gravitystorm** [comment] 2020-03-06 11:11
I don't claim any rights in the (tiny) part of the API that I designed.

**Comment by IgnoredAmbience** [comment] 2020-03-06 13:07
I did not contribute to any API/XML design work.

**Comment by crschmidt** [comment] 2020-03-06 13:10
I don't believe I had any significant role in this, but if I did, I
disclaim any and all rights that I might have in any OSM API design.

**Comment by gravitystorm** [comment] 2020-04-08 08:37
I'm going to close this issue, since it's been open for more than 30 days and there's no action for the current development team.

If anyone tagged on the original comment wants to respond here, even though the issue is closed,  then please feel free to do so.

**Closed by gravitystorm** 2020-04-08 08:37 UTC
