### ISSUE TITLE
SSL Certificates missing in docker container

### ISSUE THREAD

**Issue by SlowMo24** [openstreetmap/openstreetmap-website#4100] opened 2023-07-19 20:15 UTC
### How to reproduce the issue?

Running `docker compose build` in the [Docker](https://github.com/openstreetmap/openstreetmap-website/blob/master/DOCKER.md) setup returns

```
 => ERROR [web  3/10] RUN curl -OL https://github.com/openstreetmap/osmosis/releases/download/0.47.2/osmosis-0.47.2.tgz  && tar -C /usr/local -xzf osmosis-0.47.2.tgz                                 0.7s
------                                                                                                                                                                                                     
 > [web  3/10] RUN curl -OL https://github.com/openstreetmap/osmosis/releases/download/0.47.2/osmosis-0.47.2.tgz  && tar -C /usr/local -xzf osmosis-0.47.2.tgz:                                            
0.270   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                      
0.270                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0.640 curl: (60) SSL: no alternative certificate subject name matches target host name 'objects.githubusercontent.com'
0.640 More details here: https://curl.se/docs/sslcerts.html
0.640 
0.640 curl failed to verify the legitimacy of the server and therefore could not
0.640 establish a secure connection to it. To learn more about this situation and
0.640 how to fix it, please visit the web page mentioned above.
------
failed to solve: process "/bin/sh -c curl -OL https://github.com/openstreetmap/osmosis/releases/download/0.47.2/osmosis-0.47.2.tgz  && tar -C /usr/local -xzf osmosis-0.47.2.tgz" did not complete successfully: exit code: 60
```

This can be solved by installing `ca-certificates` in the docker.

### Screenshot(s) or anything else?

I will provide a PR in a few minutes.

**Comment by SlowMo24** [comment] 2023-07-19 20:37
Related: #3943

**Comment by tomhughes** [comment] 2023-07-19 21:17
If you have a fix just open a PR for it - there is no need to open a duplicate issue.

**Comment by tomhughes** [comment] 2023-07-19 21:20
I don't think it should be our job to provide a CA root of trust for public certificate though - that should come from the underlying container.

Certainly as far as I know we have never seen this so I'm interested to know what is different for you.

I don't recommend trying to populate an API database with omosis anyway, or indeed using docker to work on this code.

**Comment by SlowMo24** [comment] 2023-07-20 19:58
Most containers I used that use curl also installed that package. The alternative would be to use the `-k` flag for curl, I guess.

> I don't recommend trying to populate an API database with omosis anyway, or indeed using docker to work on this code.

I use this container as the fastest option to get a sample rails-port database for a database course I'm teaching. Maybe there are other options but this is just too straight forward for me.

**Comment by tomhughes** [comment] 2023-07-20 21:12
Oh I missed that - yes installing that package is fine, that's is using the underlying OS which is what I was saying it should do.

**Comment by gravitystorm** [comment] 2023-07-26 12:58
> Certainly as far as I know we have never seen this so I'm interested to know what is different for you.

This is an important point. We run the docker build process in CI, and so if it didn't work (e.g. needed the `ca-certificates` package), then it would fail in CI and we would know about it. Here is an extract from the most recent CI build, which shows the download working:

```
Step 4/12 : RUN curl -OL https://github.com/openstreetmap/osmosis/releases/download/0.47.2/osmosis-0.47.2.tgz  && tar -C /usr/local -xzf osmosis-0.47.2.tgz
 ---> Running in af9835f3f0f3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 12.5M  100 12.5M    0     0  37.6M      0 --:--:-- --:--:-- --:--:-- 37.6M
Removing intermediate container af9835f3f0f3
```
https://github.com/openstreetmap/openstreetmap-website/actions/runs/5659920570/job/15334497068#step:4:3701

I've also tested it myself, and the docker build succeeds without needing this package installation.

Do you have any ideas why it works in CI and for me, but not for you? Or was it a transitory problem? If you can reproduce this, that would be ideal.

**Comment by gravitystorm** [comment] 2023-10-04 17:51
I'm going to close this, since the Docker build continues to work in CI and we don't have any steps to reproduce.

**Closed by gravitystorm** 2023-10-04 17:51 UTC
Labels: support
