### ISSUE TITLE
recent notification emails are missing links

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#2930] opened 2020-11-02 11:43 UTC
I just noted that recent emails to notify about comments on diary posts are missing the links at the bottom. Previously, there were links like these:
You can also read the comment at https://www.openstreetmap.org/user/woodpeck/diary/393947#comment48055
and you can comment at https://www.openstreetmap.org/user/woodpeck/diary/393947#newcomment
or send a message to the author at https://www.openstreetmap.org/message/new/trial?message%5Btitle%5D=Re%3A+Why+I+am+mapping+trees

OpenStreetMap

**Comment by mmd-osm** [comment] 2020-11-02 14:46
Probably a duplicate of #2903

**Comment by gravitystorm** [comment] 2020-11-02 16:32
Thanks @mmd-osm - yes, this is a duplicate of #2903

**Closed by gravitystorm** 2020-11-02 16:32 UTC
