### ISSUE TITLE
Пакеты правок с обсуждениями были видны на страницы

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2482] opened 2019-12-26 17:36 UTC
Пожалуйста сделайте что бы пакеты правок с обсуждениями были видны на страницы, и разбить их на 2: 
1. обсуждение моих пакетов правок, 
2. обсуждение к чужим пакетам правок.

**Comment by tomhughes** [comment] 2019-12-28 10:08
Translation:

> Please make the edit packages with discussions visible on pages, and break them into 2:
> 
> 1. discussion of my edit packages,
> 
> 2. discussion to foreign packages of edits.

I'm not entirely clear what pages are being referred to though, or what a foreign edit is.

**Comment by saintamh** [comment] 2020-02-07 21:39
I'm not a native speaker of Russian but I believe a better translation would be

> Please could we make discussed changesets visible on a page, broken into two:
> 1. discussions of my own changesets
> 2. discussions of other's changesets

So, as I understand it what's described here is a page where I can see a list of my changesets that have comments, and a page where I can see other people's changesets that I've commented on.

I've had the same thought before -- sometimes I forget whether something was discussed in a private message or a changeset comment, and I have a hard time finding it. We have the "messages" section, I can see a list of my notes, my diary posts and my diary comments, but I don't think there's a place where I can see discussed changesets? 

https://hdyc.neis-one.org/ includes something like that, it's useful.

**Comment by saintamh** [comment] 2020-02-07 21:45
Possibly a duplicate of #842?

**Comment by gravitystorm** [comment] 2020-02-19 13:48
It's similar enough to #842 that I don't think we need two issues open. Thanks for spotting the existing issue!

**Closed by gravitystorm** 2020-02-19 13:48 UTC
