### ISSUE TITLE
Allow login via more than JUST ONE of Github, Facebook, etc.

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1363] opened 2016-11-09 15:35 UTC
User usually logs in by pressing the Facebook logo.

If one day the user presses the Github logo, he will enter a confusing
state...

OK now he presses Log In again and logs in with the Facebook logo.

Now he digs down and in settings, he finds a drop down menu where
apparently one selects only ONE of Github, Facebook, etc.

Please allow login via more than one of Github, Facebook, etc.

Yes, after login there should be my same smiling face in the corner
meaning I have logged in to my same openstreetmap account -- just that
today I have selected a different logo from the bottom there on the Log
In page. Thanks.

**Comment by tomhughes** [comment] 2016-11-09 16:05
Duplicate of #1274

**Closed by tomhughes** 2016-11-09 16:05 UTC
