### ISSUE TITLE
Update URL at the end of the gesture, not during

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3173] opened 2021-04-13 00:49 UTC
The [Chrome team confirms](https://bugs.chromium.org/p/chromium/issues/detail?id=1182989#c11), the OSM website should update the URL at the end of the gesture, not during!

**Comment by Firefishy** [comment] 2021-04-13 02:05
This issue likely lives with LeafletJS and not here.

**Comment by tomhughes** [comment] 2021-04-13 06:05
Well maybe - certainly we have absolutely no code of our own that has anything to do with gestures.

It would probably help if @jidanni clarified what gesture he is referring to.

**Comment by HolgerJeromin** [comment] 2021-04-13 11:18
From the linked issue tracker:

> The page is updating the url, which triggers updating history. On the desktop, the url only changes when the mouse is released. Seems like the right solution is for the page to update at the end of the gesture, not during.

Seems like we should move code from `touchmove` to `touchend`. No idea if this url history manipulating is done here or a leaflet plugin.

**Comment by tomhughes** [comment] 2021-04-13 11:35
The only references to `touchmove` are actually in iD

That said, as I say, we really need to know what gesture he is talking about!

**Comment by jidanni** [comment] 2021-04-14 10:24
ID does not have the problem. Openstreetmap website has the problem. All you need to do is move the map around and you'll see how many history entries it generates. It's like a DDOS job on the browser 's history list. Please be sure to use the same operating system as mentioned in the Chrome bug report. Thanks.

**Comment by tomhughes** [comment] 2021-04-14 10:35
So that has absolutely nothing to do with gestures then, which would explain the confusion, or at least not directly.

Rather it is triggered by leaflet's moveend events - there are a variety of ways those can happen some of which may be gesture related but there's no immediate reason to believe that it generates more than it should.

Do you actually get multiple history entries for a continuous move, or just one after each move?

**Comment by tomhughes** [comment] 2021-04-14 10:36
In case this is a duplicate of #506.

**Closed by tomhughes** 2021-04-14 10:36 UTC
