### ISSUE TITLE
Sharing route lacks route

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1681] opened 2017-11-16 04:12 UTC
1. Visit http://www.openstreetmap.org/directions?engine=osrm_car&route=24.16509%2C120.86437%3B24.16453%2C120.86329
2. Push "Share"
It is not sharing what the user thought was being shared.
The user will not know until his friends ask him where the route he was talking about is.

**Comment by tomhughes** [comment] 2017-11-16 07:04
Duplicate of #905.

**Closed by tomhughes** 2017-11-16 07:04 UTC
