### ISSUE TITLE
Add option to change interface language

### ISSUE THREAD

**Issue by royjor2016** [openstreetmap/openstreetmap-website#4623] opened 2024-03-25 18:39 UTC
### URL

https://www.openstreetmap.org/

### How to reproduce the issue?

1. is your ui language english?
2. if yes, what if you are a person who doesnt read english? how do you change it to your native lang?
3. if no, try changing it to english. where is the setting?

### Screenshot(s) or anything else?

all these websites have no option to change ui lang, and they show me something i dont understand. no helpful resource at all for non-registered users.

1. https://www.openstreetmap.org/
2. https://www.openstreetmap.org/help 
3. https://community.openstreetmap.org/ 

only https://osmfoundation.org/wiki/Main_Page has the option to change ui lang.

**Comment by royjor2016** [comment] 2024-03-25 19:18
decade old unresolved problem
https://help.openstreetmap.org/questions/1966/how-to-select-language-for-main-map-page

**Comment by tomhughes** [comment] 2024-03-25 21:44
Duplicate of #1115.

**Closed by tomhughes** 2024-03-25 21:44 UTC
