### ISSUE TITLE
iPad: Cannot reach comment button

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#2963] opened 2020-11-15 20:16 UTC
Goal: Comment on a node on an iPad. 

Setup: I think this was in Chrome for iPad.
I had the external iPad keyboard attached (so no software keyboard visible).

Issue: I cannot reach the comment-button below the text area. 
I can see it, once I drag the view up and hold my finger, but in this action I cannot also press the button.

Workaround: If I remember correctly, I was able to tab to the button and press enter, but I am not sure (the screenshots are a bit older).

Link for testing: https://www.openstreetmap.org/note/2421292

Thats what it looks like:
![IMG_1194](https://user-images.githubusercontent.com/111561/99195628-15846b00-2787-11eb-87cf-1248332e8726.jpg)

This is while dragging the view up:
![IMG_1195](https://user-images.githubusercontent.com/111561/99195634-1a491f00-2787-11eb-937b-e1b385cc00b9.jpg)

**Comment by SomeoneElseOSM** [comment] 2020-11-15 20:23
Are you sure it wasn't Safari?  See https://github.com/openstreetmap/openstreetmap-website/issues/2811 , https://github.com/Leaflet/Leaflet/issues/7255 and links from there.

**Comment by tomhughes** [comment] 2020-11-15 22:35
Duplicate of #2811.

**Closed** 2020-11-15 22:35 UTC

**Comment by HolgerJeromin** [comment] 2020-11-16 16:54
> Edit: Actually, thinking about it - any browser on iOS is going to be Safari-based, isn't it?

Yes
