### ISSUE TITLE
Names/numbers of tracks at stations in the "Standard" map layer

### ISSUE THREAD

**Issue by OpenGreenStreet** [openstreetmap/openstreetmap-website#4615] opened 2024-03-22 14:49 UTC
### Problem

I would like to urgently request that the names/numbers of the tracks at stations are also displayed in the "Standard" map layer. This way I don't have to change the map layer when searching.

Additionally: In the standard map I cannot see the names of the tracks and in the traffic map it is difficult to recognize the exits/stairs of the tracks.

**Comment by gravitystorm** [comment] 2024-03-22 14:58
Duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/3659

Please @OpenGreenStreet , we've [had this conversation about where to report such issues already](https://github.com/openstreetmap/openstreetmap-website/issues/3659#issuecomment-1222721799).

**Closed** 2024-03-22 15:02 UTC

**Comment by OpenGreenStreet** [comment] 2024-03-22 15:46
@tomhughes , @gravitystorm 
Hi guys, yes I remember. Sorry to have caused you trouble. (At the same time, I get annoyed at the lack of information in the standard view every time I travel via a station I don't know ...)
