### ISSUE TITLE
Note 1396945 is causing Application Error (HTTP 500)

### ISSUE THREAD

**Issue by maraf24** [openstreetmap/openstreetmap-website#3188] opened 2021-04-30 10:35 UTC
URL: https://www.openstreetmap.org/note/1396945

Result:
![image](https://user-images.githubusercontent.com/10471006/116683851-7360e400-a9b0-11eb-868e-408658519805.png)

**Comment by tomhughes** [comment] 2021-04-30 10:47
Duplicate of #2146.

**Closed by tomhughes** 2021-04-30 10:47 UTC
