### ISSUE TITLE
share makes HTTP url even when connecting via HTTPS

### ISSUE THREAD

**Issue by eighthave** [openstreetmap/openstreetmap-website#870] opened 2015-01-12 18:33 UTC
I connect to https://www.openstreetmap.org/#map=14/48.2019/16.3470&layers=C, then I click on "Share on the right menu, and it offers to create only an HTTP link.  The share feature should use the same scheme as the current connection, or always use HTTPS, to prevent inadvertent privacy leaks.

**Comment by genodeftest** [comment] 2015-03-22 20:12
To fix this for short URLs the osm.org server has to get a new certificate. This depends on #862 which depends on openstreetmap/operations#2.

**Comment by AngryUbuntuNerd** [comment] 2016-08-30 13:49
Has there been any progress on this? Just bumped into the same issue myself, due to mixed content  on the embedding website the snippet was not working out-of-the-box. For the share-user this will seem like a bug and be a disappointing experience.

**Comment by tomhughes** [comment] 2016-08-30 14:17
What progress is there to be made?

There's no logical reason why visiting osm.org over https should lead to the shared URL being https or vice versa - whether you need https or not depends on the site you are embedding in not on how you visit osm.org so the only thing we could really do is to add a checkbox to allow you to choose to generate https without having to add the 's' yourself.

If mean progress on gettting a certificate for the short name then no - getting it is not the problem, the problem is that we need to wait for the penetration of newer JOSMs that can support letsencrypt to increase before we can switch.

**Comment by eighthave** [comment] 2016-08-30 15:03
There is a strong logical reason to give HTTPS when the user connects
via HTTPS.  Seeing the green HTTPS on the URL bar is a promise that the
whole site is using an encrypted connection at that point in time.
Providing a HTTP link to the same content that the user is currently
viewing via the green HTTPS bar is a violation of that contract.

**Comment by genodeftest** [comment] 2016-08-31 08:00
@tomhughes Why not share HTTPS URLs by default? Shared URLs are meant to be used by end-users, not by stuff like JOSM. End users use browsers which usually are modern enough to use HTTPS URLs. Those rare cases who don't, can't even use google or facebook or wikipedia or any other major website out there any more.

**Comment by tomhughes** [comment] 2017-02-18 12:51
With the switch to letsencrypt (so we now have a certificate for osm.org) and the addition of 77fee91785af7630f608c41041cf4eeed6eeb369 and b170c06d5cd77d15d36105e6530ec99eb7e390e9 we now preserve the protocol so that the links will be https when visiting over https.

**Comment by genodeftest** [comment] 2017-02-18 15:33
@tomhughes: One of your commits introduced a new bug. Now when sharing a URL, it starts with `http:://www.openstreetmap.org/` or `https:://www.openstreetmap.org`. Note the double colons.

**Comment by tomhughes** [comment] 2017-02-18 15:39
Fixed in 7a0766a5e6dc3ab85f71a27fef8b049e56ef03b8.

**Closed by tomhughes** 2017-02-18 15:39 UTC
