### ISSUE TITLE
Changeset icons are overlapping

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3735] opened 2022-10-04 23:11 UTC
### How to reproduce the issue?

https://www.openstreetmap.org/changeset/127015913

In the changeset details there are two walls
https://www.openstreetmap.org/way/1100943495
https://www.openstreetmap.org/way/1100943494

The second shows up thicker than the first, while they're identically tagged `barrier=wall` and there's only [one image](https://www.openstreetmap.org/assets/browse/wall.20-29d59d3c20f1f6407cb1a707fb28499dcafd18283520158ed03b7c35f9c7da43.png) for a wall.

Windows 7, 10 Chrome 106.0.5249.91 (on 100% zoom and other, non-adjacent zoom levels above it)
This issue also appears on other browsers when increasing the zoom

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/67521919/193946519-9bacd505-3138-40c6-908f-fe2af11c16e4.png)

**Comment by openbrian** [comment] 2022-10-18 03:17
When I use Firefox and zoom in (control + mouse wheel), I can see that the second wall image is thicker.

But if I use dev tools and tinker with the font size, or line height, I can sometimes get the first line to be the thicker one.

I feel this issue is more about how a browser renders a 1 pixel tall image.  Some times it will be on 1 pixel and sometimes more than 1 pixel.

This bug most likely has nothing to do with source code.  It might be mitigated with source code.  Not sure it's worth putting in a crutch for this.

**Comment by mmd-osm** [comment] 2022-12-05 21:54
I don’t see any difference on my mobile. I’m also voting to close the issue (low impact, browser specific/cannot reproduce).

**Closed** 2022-12-07 20:44 UTC
Labels: bug, ui
