### ISSUE TITLE
CONFIGURE.md fails

### ISSUE THREAD

**Issue by Terrific-dev** [openstreetmap/openstreetmap-website#2523] opened 2020-01-27 17:34 UTC
I try to follow openstreetmap-website's CONFIGURE.md and i reached the point of loading an extract with Osmosis. I run this code; 

osmosis --read-pbf greater-london-latest.osm.pbf 
>   --write-apidb host="localhost" database="openstreetmap" \
>   user="openstreetmap" password="" `validateSchemaVersion="no"

then i get this;

`Jan 27, 2020 6:28:08 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Argument 7 doesn't contain a value after the '=' (ie. name=value).
	at org.openstreetmap.osmosis.core.cli.CommandLineParser.parseTask(CommandLineParser.java:281)
	at org.openstreetmap.osmosis.core.cli.CommandLineParser.parse(CommandLineParser.java:75)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:74)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
`
I've tried to put the pbf file in the openstreetmap-website directory to see if it helps, no luck. The role openstreetmap doesn't exist so i put my own credentials. It worked - kinda - but it can't connect to the database. And i also got a severe error which said that task 1-read-pbf failed.

What should i do? help

I'm trying to run an OSM-server with fictional stuff in it. Mapping of course.

**Comment by tomhughes** [comment] 2020-01-27 17:54
Duplicate of #1803.

That said I don't believe osmosis is currently capable of loading data into an up to date copy of the rails code, and there is no other known way to do so.

**Closed by tomhughes** 2020-01-27 17:54 UTC

**Comment by Terrific-dev** [comment] 2020-01-27 18:07
I've looked at stuff, and I don't think this is a duplicate of issue 1803. The user openstreetmap doesn't exist, and what you said, 

> That said I don't believe osmosis is currently capable of loading data into an up to date copy of the rails code, and there is no other known way to do so.

Then why is it included in CONFIGURE.md?

I need concrete help. I am creating a server and i am lost. I need to edit data and render new data. -Terrific-dev

**Comment by gravitystorm** [comment] 2020-01-27 18:12
> I need concrete help. I am creating a server and i am lost. I need to edit data and render new data.

We can help you with installing your development environment, up to and including getting the tests passing. But we don't have enough people here to provide support with other things like production deployments, loading data extracts, or topics like that.

There are other channels, like https://help.openstreetmap.org (mentioned in the linked issue) that can be used if you need them.

**Comment by Terrific-dev** [comment] 2020-01-27 19:10
that means i can ask the same question there? I have the exec ruby stuff ready but i need help ONLY in configure.md

otherwise thanks

**Comment by tomhughes** [comment] 2020-01-27 19:13
You can ask but as I say I'm not sure there is currently any way to do what you want - at the very least you will either need to revert he commit that removed the `users.nearby` column from the database or change osmosis to stop it trying to load that column.

Either that or you will have to find some other way to load data into the database.

Please understand that loading data into an API database is not something we ever need to do so it's not really a supported operation - the hints in CONFIGURE.md are simple attempting to help by providing what was until recently the best way to do it, a way that sadly has stopped working.

**Comment by Terrific-dev** [comment] 2020-01-27 19:15
Oh. Well, the purpose of my server is SIMPLY to create a fictional world. Is there any rendering stuff out there, i have seen switch2osm, but i have developed the ror

**Comment by Terrific-dev** [comment] 2020-01-27 19:15
ror = ruby on rails
