### ISSUE TITLE
Get rid of spam messages the user has sent when getting rid of spam accounts

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3159] opened 2021-04-02 23:42 UTC
To report spam we [read](https://github.com/openstreetmap/openstreetmap-website/issues/3127#issuecomment-797643205) we are supposed to click their account on
![20210403T073902](https://user-images.githubusercontent.com/1230959/113461630-ea599a00-944f-11eb-9ff2-632f64cbb1b7.jpg)

OK, we do, and
![20210403T074111](https://user-images.githubusercontent.com/1230959/113461662-03fae180-9450-11eb-9c96-cac3c125c900.jpg)

Therefore, I have an idea:
Get rid of spam messages the user has sent when getting rid of spam accounts.
Thank you.

**Comment by tomhughes** [comment] 2021-04-02 23:52
Duplicate of #3158.

**Closed by tomhughes** 2021-04-02 23:52 UTC
