### ISSUE TITLE
Tiles not loading properly when opening notes link on phone

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/openstreetmap-website#2349] opened 2019-08-17 08:30 UTC
Hey, usually I do not have issues with the website, but the tiles, *never* load as they should on my phone. On my Mac, they loas fine.

Using Chrome Beta on a One Plus 5 with Android 9.

When loading the page, only the tiles at the left load. The right stays gray. Panning around the map does not load tiles. When going to another tab in chrome and then revisiting the OSM tab, all tiles load properly.

Example: https://www.openstreetmap.org/note/1885992#map=14/38.5414/-0.1020

![Screenshot_20190817-102808](https://user-images.githubusercontent.com/3776997/63208848-bba37a00-c0d9-11e9-9377-7797ba5e1320.jpg)

**Comment by mmd-osm** [comment] 2019-08-17 10:44
That's really duplicate of #2035.

**Closed** 2020-04-15 14:50 UTC
