### ISSUE TITLE
Center displaced and does not render tiles on history mode in mobile

### ISSUE THREAD

**Issue by smaprs** [openstreetmap/openstreetmap-website#1867] opened 2018-05-16 13:13 UTC
I've posted this issue wronlgy at
https://github.com/gravitystorm/openstreetmap-carto/issues/3237
and was told to post it here, thanks:

Expected behavior
Renders standard OSM tiles normally on mobile (cellular android) on history mode.

Actual behavior
Renders only some standard OSM tiles, but blank tiles for the rest, on mobile, on history mode:
like in openstreetmap.org/history#map...
They got truncated at half screen more or less. Also center is displaced when history mode is open.
Also it shows not well the changeset frames in the area, it shows just as a thiny trace, not as an area.
So can't chose a changeset to verify.
It happens only on mobile and on history mode.
When disabled history mode, rendering returns to normal.
Some other fellow mappers have reported same problem.

Links and screenshots illustrating the problem
![image](https://user-images.githubusercontent.com/29050750/40118817-5c6b34ca-58f1-11e8-9cdc-b2640381ca5e.png)

**Comment by mmd-osm** [comment] 2018-05-16 13:30
That's a duplicate of #1663

**Closed** 2018-05-16 13:42 UTC
