### ISSUE TITLE
Retitle "Where am I" to "Where is this"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1100] opened 2015-12-06 12:54 UTC
I am looking at a map of Calcutta. I am in Taiwan.
I click Where am I, the results are Calcutta.
Where am I always refers to location / GPS based services on all other sites.

**Comment by danstowell** [comment] 2015-12-06 12:58
(Issue #412)

**Comment by jidanni** [comment] 2015-12-06 12:58
Also no crosshairs appear while we are clicking, however an precise log/lat pair is shown. One cannot easily center the map to get the coordinates of a point without crosshairs. One assumes the coordinates are the center. Google would surely drop a pin.

**Comment by tomhughes** [comment] 2015-12-06 12:59
Duplicate of #412.

**Closed by tomhughes** 2015-12-06 12:59 UTC

**Comment by tomhughes** [comment] 2015-12-06 13:00
Sorry, when are you clicking? The "where am I" link does give you a chance to click on the map, it just does a reverse geocode for the center of the map.

Showing the coords is just a side effect of the way it works - the use case was for when you follow a link from another site to a highly zoomed in map and want to get a description of where you are.

Personally I just zoom out instead, but people asked for this...

**Comment by jidanni** [comment] 2015-12-06 13:02
Oh and a pin appears, but only if one happens to mouseover the lat/long...

**Comment by jidanni** [comment] 2015-12-06 13:19
Anyways, most will think "where am I" will do what "Go to home location" does. But there are three different things: Home that I set, HTTP API current location, current place I am looking at...

Go to home location sounds worse that what Google would call it.

OK I am getting off track.

Anyways, the user still must find the center by trial and error.
