### ISSUE TITLE
Allow using geo: strings in the search box

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3818] opened 2022-11-25 00:28 UTC
Currently one was trim the "geo:"  off for this search to work.  
![Screenshot_20221124-182405_Chrome Dev.jpg](https://user-images.githubusercontent.com/1230959/203877745-30b90694-7d2b-4869-87e7-1242ce36a9e1.jpg)

**Comment by mmd-osm** [comment] 2022-11-25 06:50
Duplicate of #1123

**Closed** 2022-11-25 07:05 UTC
