### ISSUE TITLE
What happened to the notes on the map?

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3996] opened 2023-04-01 17:32 UTC
Have there been any recent changes to the code regarding the display of notes?

So far, when I opened the map of my city on zoom 12, I could see all the notes (about 100). Now I see only a dozen or so. Zooming in to z13 or z14 doesn't show all the notes either. What happened? Is it a bug or a deliberate action? I don't know how to look for notes now.

**Comment by danieldegroot2** [comment] 2023-04-01 18:50
This issue is likely a duplicate of (part of) #3831; a note in view may be causing a javascript error, causing some notes not to display.

**Comment by maro-21** [comment] 2023-04-01 19:10
I think this problem with the notes started in early March.

**Comment by danieldegroot2** [comment] 2023-04-01 19:28
Could you provide a link to the general area you are viewing on OpenStreetMap (without specific place selected is fine), please? Then someone else could try looking into it.

**Comment by tomhughes** [comment] 2023-04-01 22:59
There have been no such changes. Nobody has touched the notes code for many months.

**Closed by tomhughes** 2023-04-01 22:59 UTC

**Comment by maro-21** [comment] 2023-04-01 23:09
> There have been no such changes. Nobody has touched the notes code for many months.

Thank you for the answer.
So is this behavior related to #2146?

**Comment by tomhughes** [comment] 2023-04-01 23:50
No idea. If it is then it would require the person that opened a lot of notes in the area to have closed their account. Mostly though it's impossible to comment as you haven't provided any idea as to what area you are talking about.

**Comment by AntonKhorev** [comment] 2023-04-01 23:54
It is related to this: https://github.com/openstreetmap/openstreetmap-website/pull/3617

> So far, when I opened the map of my city on zoom 12, I could see all the notes (about 100). 

You can't see more than 100 notes with osm.org note layer.

> Now I see only a dozen or so.

You'll see notes up to the first one without visible comments, then the javascript code will fail.

> I don't know how to look for notes now.

Use my notes viewer:
https://antonkhorev.github.io/osm-note-viewer/#mode=bbox&bbox=16.7390%2C50.9398%2C17.3021%2C51.2821&closed=7&map=11/51.1074/17.0171

**Comment by maro-21** [comment] 2023-04-02 11:23
> Could you provide a link to the general area you are viewing on OpenStreetMap

https://www.openstreetmap.org/#map=12/51.1069/17.0027&layers=N


> You'll see notes up to the first one without visible comments, then the javascript code will fail.

When does this happen? Is it when the user who created or commented on the note has deleted the account?
How can one create a note without a comment? I understand that not using popular editors and OSM applications?

**Comment by tomhughes** [comment] 2023-04-02 11:46
Ah right that makes more sense now you've explained there is a javascript exception.

Yes indeed it is failing looking up the initial comment for a note, so this is indeed a duplicate of #2146.

**Comment by maro-21** [comment] 2023-04-02 12:07
> so this is a duplicate of #2146.

I think it's connected but not the same. The issue #2146 is about a server error when trying to display a note. This one is about notes not displaying on the map because of a JavaScript error.

**Comment by AntonKhorev** [comment] 2023-04-02 13:35
> > You'll see notes up to the first one without visible comments, then the javascript code will fail.
> 
> When does this happen? Is it when the user who created or commented on the note has deleted the account?

That's the most likely scenario.

> How can one create a note without a comment?

You can't: https://github.com/openstreetmap/openstreetmap-website/blob/c8f6d6df0f2d7ad15de4833e855701b05d1dde5e/app/controllers/api/notes_controller.rb#L91

> Or by "not visible comment" you mean a comment that was hidden by a moderator?

That didn't get merged too: https://github.com/openstreetmap/openstreetmap-website/pull/3438
