### ISSUE TITLE
Quotes in tag value are rendered as &quot;

### ISSUE THREAD

**Issue by i-ky** [openstreetmap/openstreetmap-website#3873] opened 2023-01-05 10:33 UTC
### URL

https://www.openstreetmap.org/way/79091438

### How to reproduce the issue?

1. Find a node, way or relation with `"` character in tag value
2. Open respective element page on openstreetmap.org website
3. Observe `"` being rendered as `&quot;`

Other special characters (e.g. `&` &rarr; `&amp;`) cause the same issue.

### Screenshot(s) or anything else?

![bug screenshot](https://user-images.githubusercontent.com/25753618/210758767-70fb2dd1-4866-4d49-aa27-a1bc8c46beae.png)

**Comment by pietervdvn** [comment] 2023-01-05 10:42
Probably a duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/3872 - or at least related.

This issue was fixed already, but not yet deployed.

**Comment by tomhughes** [comment] 2023-01-05 10:50
Yes it's a duplicate of #3872 which I didn't deploy the fix for as it was a Wednesday and I thought there might be more from @gravitystorm so I decided to wait to deploy it and then forgot. I'll do it now and it will be live in 30 minutes or so.

**Closed by tomhughes** 2023-01-05 10:50 UTC
