### ISSUE TITLE
closing search results should not change map view 

### ISSUE THREAD

**Issue by fgnievinski** [openstreetmap/openstreetmap-website#4122] opened 2023-07-30 04:34 UTC
### URL

https://www.openstreetmap.org/#map=17/-29.39659/-50.88193

### How to reproduce the issue?

1. open url above
2. search for "parque do lago negro"
3. click on the first hit to highlight it on the map
4. now click on the X button to close the search results and continue browsing the region
5. notice the feature just found by searching is no longer shown on the map

### Screenshot(s) or anything else?

![Screenshot_20230730-012742](https://github.com/openstreetmap/openstreetmap-website/assets/5018500/10a194a3-a700-45cc-8253-8897a5264bf4)
![Screenshot_20230730-013342](https://github.com/openstreetmap/openstreetmap-website/assets/5018500/321dce98-969a-41c9-8a68-2f9a3e4f41ee)

**Comment by tomhughes** [comment] 2023-07-30 07:46
Duplicate of #729.

**Closed by tomhughes** 2023-07-30 07:46 UTC
