### ISSUE TITLE
Ability to send an article in drafts in diaries, before writing it. https://www.openstreetmap.org

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2247] opened 2019-06-04 08:26 UTC
Ability to send an article in drafts in diaries, before writing it on. https://www.openstreetmap.org

Возможность отправить статью в черновики в дневниках, до ее написания на. https://www.openstreetmap.org

**Comment by mmd-osm** [comment] 2019-06-04 10:37
Duplicate of #769

**Closed** 2019-06-11 13:43 UTC
