### ISSUE TITLE
Closing notes sometimes resets the zoom

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#4256] opened 2023-09-20 17:02 UTC
### How to reproduce the issue?

1. Open the note page so that several notes are displayed on the map
2. Close the note
3. Select another note
4. Close the note
5. The zoom is reset.

### Screenshot(s) or anything else?

https://github.com/openstreetmap/openstreetmap-website/assets/25708359/e53f8680-ccee-4183-9b92-78f0faf53e2b

**Comment by danieldegroot2** [comment] 2023-09-22 22:43
This issue is a duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/648#issuecomment-1732102275 .

**Closed** 2023-09-24 17:31 UTC
