### ISSUE TITLE
Avoiding the JavaScript trap

### ISSUE THREAD

**Issue by izobin** [openstreetmap/openstreetmap-website#3220] opened 2021-06-11 08:36 UTC
Users trying to avoid the JavaScript Trap (https://www.gnu.org/philosophy/javascript-trap.html) might be using the libreJS firefox add-on. Currently, libreJS will blacklist the JS on www.openstreetmap.org. The user is then expected to look through the source-code of the webpage manually to find out if the JS is licensed as free software.

If the JavaScript that is loaded by www.openstreetmap.org is in fact free software, would you please consider "setting the JavaScript free" as described in this documentation: https://www.gnu.org/software/librejs/free-your-javascript.html ? Your website contains the following notice: "OpenStreetMap is a map of the world, created by people like you and free to use under an open license." This seems to suggest, that the code is in fact free software and it is only a matter of correctly declaring the licenses!

This way everyone can easily avoid the JavaScript Trap without having to read through the source code of the webpage, manually confirming and whitelisting the scripts.

**Comment by tomhughes** [comment] 2021-06-11 09:17
Duplicate of #2886.

**Closed by tomhughes** 2021-06-11 09:17 UTC
