### ISSUE TITLE
Change relative summary dates on user_blocks pages to absolute ones

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#907] opened 2015-02-22 19:38 UTC
It'd make the pages substantially more useful to everyone, I think - including people who have been blocked.  

The summary and individual pages currently say things like "Ends in almost 10 years" or "Ended about 12 hours ago".  There appears to be no way to obtain an exact date (such as the "hover the mouse over it" method that works where summary dates are displayed elsewhere).

I suspect that there's an issue raised elsewhere saying something like "summary times instead of absolute ones on browse pages make those pages less usable" but I can't find it right now - and this one really isn't a duplicate of that issue, since at least on browse pages if you're on a PC you can find out when "about 12 hours ago" really was by hovering the mouse over the date.

**Comment by mmd-osm** [comment] 2021-02-14 20:37
Hover mouse over it seems to work here. You need to place the mouse exactly on the relative date details, though:

![image](https://user-images.githubusercontent.com/5842757/107888463-a0067300-6f0c-11eb-9d6c-f933979b97da.png)

**Comment by SomeoneElseOSM** [comment] 2021-02-14 20:42
The "hover the mouse over it thing has been made to work at some point in the last 5 years.

However, the mere fact that you have to bugger about and "place the mouse exactly on the relative date details" makes it a pain to use.  Also, how do I do that on a phone?

**Comment by mmd-osm** [comment] 2021-02-14 20:45
Well, that's really a general issue with those tooltips on mobile devices, they don't work for changeset details either.

**Comment by SomeoneElseOSM** [comment] 2021-02-14 20:47
> Well, that's really a general issue with those tooltips on mobile devices, they don't work for changeset details either.

It'd be good to change those to proper dates too (but that's somewhat beyond the scope of this issue)

**Comment by polarbearing** [comment] 2021-02-16 15:25
I've never understood what relative dates are useful for, in general. In one of my browsers I have a greasemonkey script that adds the absolute ones here on GitHub. 
For changesets as well as block messages I need to compare the timeline of events in detail, rough rounding to large time units like months and years is not helpful, and even 'a minute ago' is invalid once the tab is open for an hour.

In case there are people who like them, a switch in the profile settings might help.

related discussion:
#798 relative time in RSS feeds

**Comment by HolgerJeromin** [comment] 2021-02-25 07:55
Kind of duplicate of #631

**Comment by tuckerrc** [comment] 2021-02-25 21:02
@polarbearing One of the biggest benefits (IMHO) of relative dates is the ability to ignore all the timezone weirdness in the world. With a relative date everything is calculated from the timezone of the server.

**Comment by polarbearing** [comment] 2021-02-26 15:29
Right if you aggregate all events that happened over a 360 day timeframe to "4 years ago", you don't need to care about timezones. But that fuzziness is not what I need.

**Closed** 2024-12-10 19:11 UTC
Labels: ui
