### ISSUE TITLE
list changeset comments

### ISSUE THREAD

**Issue by fkv1** [openstreetmap/openstreetmap-website#1094] opened 2015-11-26 07:38 UTC
In the user profile page (www.openstreetmap.org/user/[username]), there is a menu-like line containing the links "My Edits", "My Notes", "My Traces", "My Diary", "My Comments" and "My Settings", where "My Comments" means comments to diary entries. There should also be a link to a list of all changeset comments the user made (or a list of all changesets the user commented on), because it is currently impossible to retrieve them. (I often do remember that I made a certain changeset comment, but I don't remember the changeset ID.) The list should at least include the comment date (or the latest comment date), the user who made the changeset, and the changeset ID.

In order to avoid confusion with comments on diary entries, the link to those should certainly be renamed like "My Diary Comments", while the new link will be "My Changeset Comments".

**Comment by tomhughes** [comment] 2015-11-26 08:43
Duplicate of #842.

**Closed by tomhughes** 2015-11-26 08:43 UTC
