### ISSUE TITLE
User Changeset Feed Defaults to Last Editor If Specified User Doesn't Exist

### ISSUE THREAD

**Issue by iandees** [openstreetmap/openstreetmap-website#46] opened 2012-05-01 19:20 UTC
If someone requests a changeset feed for a user that doesn't exist, the feed should give an HTTP 404. It currently seems to give a valid feed for the user that edited most recently.

**Comment by gravitystorm** [comment] 2017-03-30 13:41
I can't reproduce the originally reported issue. A lot of the code in this area has changed since 2012 so I'm marking this as closed. If anyone can reproduce it then of course we'll reopen.

**Closed by gravitystorm** 2017-03-30 13:41 UTC
Labels: bug
