### ISSUE TITLE
Incomplete key for Cycle layer

### ISSUE THREAD

**Issue by Wuzzy2** [openstreetmap/openstreetmap-website#1320] opened 2016-10-12 13:56 UTC
The Cycle layer now has a very basic key but it is also slightly incomplete.
A few symbols are missing, also most area colors are missing, too. Notably, some street types like service or track are missing.

This page documents more symbols (but not much else):
http://opencyclemap.org/docs/

The key above is not complete either, as area colors are not documented. Rendering of most streets is left unexplained either. The key for highway=track and highway=service is missing both on www.openstreetmap.org and opencyclemap.org. I suppose there are a couple of things which are rendered but not part of either key, and I am not even aware of.

To my knowledge, the OpenCycleMap style is kept secret for some reason (so much for “Open” xD. But correct me if I'm wrong). The author(s) of this style can help us by:

* Releasing the OpenCycleMap into the public, or
* Completing the key written down at http://opencyclemap.org/docs/, or
* Doing both.

**Comment by tomhughes** [comment] 2016-10-12 14:03
Duplicate of #982.

**Closed by tomhughes** 2016-10-12 14:03 UTC
