### ISSUE TITLE
iPad: Query-Button does not work

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#2964] opened 2020-11-15 20:33 UTC
When I am on an iPad (eg here https://www.openstreetmap.org/#map=15/52.4703/13.4443), the query-button does not do anything. I can tab it, but nothing happens. The note button on the other hand does open the side panel as expected.

Screengrab: I click the notes to see that things happen. You then see the query button flickering with nothing happening, when I tab in the map.

![RPReplay_Final1604613217 m4v](https://user-images.githubusercontent.com/111561/99196054-369a8b00-278a-11eb-97d7-195e2bf10c9d.gif)

**Comment by tomhughes** [comment] 2020-11-15 22:35
Duplicate of #2811.

**Closed by tomhughes** 2020-11-15 22:35 UTC
