### ISSUE TITLE
Opening note leads to internal server error

### ISSUE THREAD

**Issue by Discostu36** [openstreetmap/openstreetmap-website#3931] opened 2023-02-12 13:28 UTC
### URL

https://www.openstreetmap.org/note/3312846

### How to reproduce the issue?

1. Open url mentioned above
2. Behold the Internal Server Error

### Screenshot(s) or anything else?

![grafik](https://user-images.githubusercontent.com/30999326/218313682-c6209198-a525-4dea-9297-18b7e7f2d35c.png)

The note is visible in ID:
![grafik](https://user-images.githubusercontent.com/30999326/218313760-7a510227-e65b-4553-becf-05aeaf943cb4.png)

In NotesReview I can even read the initial comment:

![grafik](https://user-images.githubusercontent.com/30999326/218313839-582df988-8db1-455c-9c38-f594dca23a40.png)

But the note is not visible on the osm.org note layer:

![grafik](https://user-images.githubusercontent.com/30999326/218313782-9c5bafd6-0a8b-4011-9bdf-cff637662c98.png)

**Comment by Discostu36** [comment] 2023-02-12 13:34
This also happens with other notes:

https://www.openstreetmap.org/note/3278629
https://www.openstreetmap.org/note/3314745

**Comment by tomhughes** [comment] 2023-02-12 13:46
Duplicate of #2146.

**Closed by tomhughes** 2023-02-12 13:46 UTC
