### ISSUE TITLE
Feature Request: History View: Colorize altered tags 

### ISSUE THREAD

**Issue by martinstingl** [openstreetmap/openstreetmap-website#3122] opened 2021-03-04 19:48 UTC
Idea: In the history view of an object colorize/mark the tag rows like this:
green: added tag
yellow: changed tag
red (in previous changeset): deleted tag

**Comment by mmd-osm** [comment] 2021-03-04 20:01
Duplicate of #1253

**Closed** 2021-03-04 20:31 UTC
