### ISSUE TITLE
Keyboard navigation: Consistent focus indication for user profile button

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3639] opened 2022-07-29 12:21 UTC
### Description

No focus is shown on the profile button (while closed) when using Tab to navigate to it. The user gets no visual indication the profile button is currently selected.

The Edit / More edit options / History / Export buttons give the highlight they would as if they were clicked on / open.

I'd suggest choosing a consistent way to show focus for these buttons. For example
- Use the default highlight if possible; or
- Extend the current behaviour (may be misleading)

**Comment by tomhughes** [comment] 2022-07-29 12:27
I certainly get a highlight - this is after I tabbed to History:
![image](https://user-images.githubusercontent.com/147741/181758288-ab25b268-1ac1-4910-8b2d-98c9e2de9e83.png)

**Comment by tomhughes** [comment] 2022-07-29 12:28
Oh sorry you said those do - so which button do you mean by the "profile" button? The menu trigger in the top right?

**Comment by danieldegroot2** [comment] 2022-07-29 12:31
Yes

**Comment by gravitystorm** [comment] 2022-07-29 12:49
Duplicate of #3633

**Closed by gravitystorm** 2022-07-29 12:49 UTC
