### ISSUE TITLE
generate https short links

### ISSUE THREAD

**Issue by httpless** [openstreetmap/openstreetmap-website#1440] opened 2017-02-16 21:29 UTC
Currently the main website is using secure HTTPS for connections but when you have the site generate a short link it generates an insecure HTTP link.

I would like to suggest to increase security, privacy and integrity for users when sharing the short links that they be generated to use HTTPS instead.

This would need SSL certs to be updated to support the osm.org domain

**Comment by tomhughes** [comment] 2017-02-16 22:16
Duplicate of #870.

**Closed by tomhughes** 2017-02-16 22:16 UTC
