### ISSUE TITLE
Language of headers vs. names

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3094] opened 2021-02-15 01:26 UTC
Here we see an opposite logic is happening.
E.g., in
```
Case 3:
<title>路徑：‪Former Tianlun-Wufeng Line‬
Case 5:
<title>Way: ‪舊天輪-霧峰線‬
```

I.e., for [an object](https://www.openstreetmap.org/way/863780195) with tags
```
name	舊天輪-霧峰線
name:en	Former Tianlun-Wufeng Line
name:zh-Hant	舊天輪-霧峰線
```

So it is quite a gamble of what people we share it to will see in their
browser, depending on what their browser sends for the Accept-Language
header.

```
Case 1:
Accept-Language:
<title>Way: ‪舊天輪-霧峰線‬

Case 2:
Accept-Language: accept-language: en-US,en;q=0.9
<title>Way: ‪Former Tianlun-Wufeng Line‬

Case 3:
Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
<title>路徑：‪Former Tianlun-Wufeng Line‬

Case 4:
Accept-Language: zh-TW,zh;q=0.9
<title>路徑：‪舊天輪-霧峰線‬

Case 5:
Accept-Language: zh-Hant,zh;q=0.9
<title>Way: ‪舊天輪-霧峰線‬
```

All this if further complicated by the quasi zh-TW - zh-Hant
relationship...

[Makefile.txt](https://github.com/openstreetmap/openstreetmap-website/files/5979025/Makefile.txt)

Apparently, once there is the slightest whiff of en-US in the Accept-Language string, all priority numbers are ignored, and the English name of the object is used no matter what!

As for "Way:", a slightly different logic is apparently involved.

**Comment by tomhughes** [comment] 2021-02-15 07:07
Duplicate of #2647.

**Closed** 2021-02-15 07:07 UTC
