### ISSUE TITLE
Mobile: Edit button hidden

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#4435] opened 2023-12-25 06:21 UTC
On my iPhone I cannot see the edit button (or history / export) anymore when using the horizontal view:

![4A1D2E4F-D218-450A-B721-5590BA2C59B2_1_102_o](https://github.com/openstreetmap/openstreetmap-website/assets/111561/8852a584-bf7b-4a2c-9106-cc7cd78b13f8)

The only way to get to it is to use the turn the phone:
![3751DDF4-F4AF-4AAD-9AFA-E08300448D26_1_201_a](https://github.com/openstreetmap/openstreetmap-website/assets/111561/dee89c01-c12c-43b0-8de8-782f7c636ab4)

**Comment by Dimitar5555** [comment] 2023-12-25 07:13
I think that it is intentional but I can't find the PR/commit that made it hidden. Either way, this issue is most likely a duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/2233.

**Comment by tordans** [comment] 2023-12-25 07:25
Thanks @Dimitar5555 I was sure I used it recently and assumed it to be a side effect of some recent refactoring. I will close now in favor of the (years...) older issue.

**Closed** 2023-12-25 07:25 UTC
