### ISSUE TITLE
Bidi support for texts of diaries and changeset discussions

### ISSUE THREAD

**Issue by iriman** [openstreetmap/openstreetmap-website#1943] opened 2018-07-28 08:50 UTC
Hi, could you please make the texts of diaries and changeset discussions bidi-aware?

There is a new `dir=auto` in HTML 5.0 that will do it when applying to each paragraph but doesn't have a wide support, but there could be some scripts to implement that, something like the way more recent versions of android behave with RTL or LTR texts.

I'm not much a programmer, but please look at [this ](http://jsfiddle.net/Hcx6H/436/) basic example. 
Also [this](https://stackoverflow.com/a/41671177/3726620) explanation may be helpful.

The following screenshots are taken while my localization settings on OSM website is set on `fa` which is a RTL language, but there is some similar issues on LTR environment.

![1 1](https://user-images.githubusercontent.com/8467903/45489593-e70b3f80-b779-11e8-823a-14f60f882dc4.png)

another

![2](https://user-images.githubusercontent.com/8467903/43354792-a7e848ca-9267-11e8-9cec-124fc7adde40.png)

Another example for changeset discussion
For now we have to put each ltr word in a separate line to be displayed correctly, If the user's page is ltr (like bellow). Similar problem will occur when users's page is rtl but content of messages is ltr with some rtl words.

![1 2](https://user-images.githubusercontent.com/8467903/45489633-0013f080-b77a-11e8-97f8-f015203ee599.png)

thanks

**Comment by iriman** [comment] 2019-02-19 12:22
Maybe it's worthwhile to mention that I'm currently using an addon on _my browser_ to display _some of common_ bidirectional texts in a correct view. (See [this section on my diary](https://www.openstreetmap.org/user/iriman/diary/47568#section-4). it is in Persian but code is clear). I know it's far from what it should actually be to be used widely.

**Comment by mmd-osm** [comment] 2024-06-22 11:18
@iriman : this issue is quite old, and I'm not sure if this has been fixed in the meantime.

**Closed** 2024-06-30 16:11 UTC
Labels: i18n

**Comment by NeatNit** [comment] 2025-03-24 22:46
FWIW, this has finally been fixed for discussions yesterday in my PR #5835 and may soon be fixed for diary entries by #5840 if accepted. This issue is more-or-less a duplicate of #3428.
