### ISSUE TITLE
Provide an endpoint to link users by their id

### ISSUE THREAD

**Issue by not-my-profile** [openstreetmap/openstreetmap-website#3750] opened 2022-10-10 05:28 UTC
It should be possible to create reliable links to user profiles that do not break when they change their display name.

For example https://www.openstreetmap.org/user-by-id/16106660 would simply return a 302 temporary HTTP redirect to https://www.openstreetmap.org/user/push-f. In the case that no user by the given id exists the route would just return a 404.

The use case is that third-party services want to create reliable links to OpenStreetMap users.

See #482 for a related discussion.

**Comment by tomhughes** [comment] 2022-10-10 06:02
As you observe this is a duplicate of #482 which remains open at this time.

**Closed by tomhughes** 2022-10-10 06:02 UTC

**Comment by not-my-profile** [comment] 2022-10-10 07:17
I disagree with this being a duplicate. #482 is about changing the URL design of existing routes so that all user facing URLs become permanent. Here I suggest the addition of a separate route (that would just redirect to the current routes), which is would be easier to implement and would also be backwards compatible.

**Comment by tomhughes** [comment] 2022-10-10 07:28
It all amounts to the same thing, providing a route based on a numeric user ID and the other ticket already has a lengthy discussion of possible ways of doing that.

Of course we're well aware that we could just use a different root URL but that's also kind of ugly though we certainly haven't ruled it out.

It just makes no sense to have a second separate discussion of how to solve the same problem here.

**Comment by not-my-profile** [comment] 2022-10-10 07:55
I was seeing this as two separate problems: 1) the URLs of user profiles can break and 2) external services cannot reliably link user profiles. Introducing a separate redirecting endpoint only addresses the second problem.

But I am fine with continuing the discussion in the other issue.
