### ISSUE TITLE
URL with coordinates stopped showing pin (marker) on map

### ISSUE THREAD

**Issue by MichaelInParis** [openstreetmap/openstreetmap-website#2759] opened 2020-08-08 05:14 UTC
Until two days ago, a URL with coordinates (such as [this one](http://www.openstreetmap.org/?zoom=18&mlat=48.87030697222222&mlon=2.35643100000000)) would open the appropriate map with a marker (pin) showing the precise place corresponding to the coordinates. It still opens the correct map, but doesn't, show the marker anymore.

**Comment by matkoniecz** [comment] 2020-08-08 07:15
https://www.openstreetmap.org/images/images/marker-icon.png gets 500 internal server error

**Comment by MichaelInParis** [comment] 2020-08-08 07:19
Thanks, but why did you close this issue? It is not resolved yet as far as I can see.

**Comment by matkoniecz** [comment] 2020-08-08 07:30
I closed #2760 as it is duplicate of this one.

**Comment by MichaelInParis** [comment] 2020-08-08 07:35
Wasn't your comment about about it enough? Why did you have to close my report of 2 hours ago and add yours?

**Comment by MichaelInParis** [comment] 2020-08-08 07:37
Ah, sorry, I had misunderstood and thought you had closed this one.

**Closed** 2020-08-08 10:02 UTC

**Comment by MichaelInParis** [comment] 2020-08-08 10:05
tomhugues why on earth did you close this? It is still not working.

**Comment by tomhughes** [comment] 2020-08-08 10:12
Calm down. I closed it because I pushed a fix - it takes about half an hour for that to fully deploy to all the servers.

**Comment by matkoniecz** [comment] 2020-08-08 10:43
> It is still not working.

It is normal to close issue when fix was implemented, not when it was released. Weeks before closing issue as implemented and releasing new version is normal for many cases.

Fortunately in case of osm website deployment time is significantly quicker :)

**Comment by MichaelInParis** [comment] 2020-08-08 10:49
> It is still not working.

Indeed.
By the way, this problem affects _any_ search in OSM: the resulting map doesn't put a marker on the location.
 
> It is normal to close issue when fix was implemented, not when it was released.

May I add that a couple of words of explanation (about the fix) rather than just a link to the modified code would have been helpful. I hadn't used github in a very long time so I first didn't notice that link and when I clicked, good thing I am a computer programmer, I understood the fix. But to any user who isn't... ?

**Comment by matkoniecz** [comment] 2020-08-08 10:56
> couple of words of explanation (about the fix)

Adding such burden would not be reasonable, and nontechnical user has no need for anything in addition to "we know that it is broken, steps were taken to fix it"

**Comment by tomhughes** [comment] 2020-08-08 10:57
Look the close happens automatically when I mention the bug in the commit.

Now if you'll all just given me a minute I'll see if I can work out why the fix doesn't seem to be working in production.

**Comment by tomhughes** [comment] 2020-08-08 11:08
Right I think the deployment issues are resolved now and it should be working.

**Comment by MichaelInParis** [comment] 2020-08-08 11:34
It does indeed work again, thanks for the fix.
