### ISSUE TITLE
Please send the wishes of the developer to improve the site directly from https://www.openstreetmap.org

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2244] opened 2019-06-04 08:14 UTC
Please send the wishes of the developer to improve the site directly from https://www.openstreetmap.org

Сделайте пожалуйста, отправку пожеланий разработчика по улучшения сайта непосредственно с сайта https://www.openstreetmap.org

**Comment by tomhughes** [comment] 2019-06-04 09:42
This is a little tricky, because www.openstreetmap.org is made up of a number of components with no one correct location for requesting improvements.

Also we already get far more requests than we are able to action so all this is likely to do in the short term is to lead to disappointment.

It's not a terrible idea, but it's equally not urgent either - probably the best solution is a link on https://www.openstreetmap.org/about or something.

**Comment by simonpoole** [comment] 2019-06-04 11:35
The problem with the idea is that either users need a github login, or you need to create a specific login for reporting issues which is a bit questionable from a security pov.  

I do this with Vespucci and add the OSM display name to the report so that the use is actually contactable, see for example https://github.com/MarcusWolschon/osmeditor4android/issues/900
(because of the security concerns it doesn't actually work with thrid party builds, for example F-Droid).

**Comment by gravitystorm** [comment] 2019-07-03 13:43
Duplicate of #1390

**Closed by gravitystorm** 2019-07-03 13:43 UTC
