### ISSUE TITLE
the data took to long (object history)

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#1252] opened 2016-07-18 11:09 UTC
I know that we want to limit the impact of time consuming queries on the api server, but maybe we could offer a workaround, e.g. when the server goes in timeout, the current message: "Sorry, the data for the way with the id 304804695, took too long to retrieve." could be amended by something like this: "do you want to display only the previous version?".
Other options would be to get older data from other services like overpass.

**Comment by dieterdreist** [comment] 2016-07-18 11:34
For relations or other "big" geometries it would also be interesting to optionally only see the tags.

**Comment by mmd-osm** [comment] 2024-06-23 17:51
In the meantime, you can navigate between object versions without loading the full object history:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/68641a49-fb98-42c6-b8d0-3e36c4c28089)

**Comment by mmd-osm** [comment] 2024-06-30 16:38
Closing as duplicate of #3524

**Closed by mmd-osm** 2024-06-30 16:38 UTC
