### ISSUE TITLE
I build deployment. When i refresh, auto logout

### ISSUE THREAD

**Issue by sphr9999** [openstreetmap/openstreetmap-website#2668] opened 2020-06-25 03:45 UTC
I used Docker to deploy website to server. i Built project to deployment.
![image](https://user-images.githubusercontent.com/31273626/85650942-dd459880-b6d0-11ea-94d3-bc86e650791e.png)

when website was at edit page, with room >16 and loaded data. I refresh website, after website logout and redirect to login. I hope it redirect current page and not logout.
I clone from source code from master branch and do not edit. I don't know I forgot any configuration at where. Sorry, i do not use English well. Please help me.

**Comment by tomhughes** [comment] 2020-06-25 06:06
Duplicate of #2665

**Closed by tomhughes** 2020-06-25 06:06 UTC
