### ISSUE TITLE
Markdown support for changeset and notes discussions

### ISSUE THREAD

**Issue by srividyacb** [openstreetmap/openstreetmap-website#1257] opened 2016-07-28 10:30 UTC
OpenStreetMap Diary entries support Markdown which is very useful for community to comment, give links to resources and share images for discussions. Along with diaries, a lot of important discussions take place in changesets and notes but sadly, they do not support Markdown as of now making it difficult for many.

Thus, it would be great if we have Markdown support in changesets and notes discussions. 

cc @planemad @geohacker

**Comment by tomhughes** [comment] 2016-07-28 12:29
Duplicate of #1257.

**Closed by tomhughes** 2016-07-28 12:29 UTC
