### ISSUE TITLE
Maybe OSM search can remove commas before querying nominatum

### ISSUE THREAD

**Issue by b-jazz** [openstreetmap/openstreetmap-website#2171] opened 2019-03-06 20:41 UTC
Nominatum has no plans to fix the issue of searching for something with a comma in its name because it would involve a major change in how nominatum works. Maybe OSM could remove the comma before passing the search string off to nominatum. That would be a pretty easy, if not hacky, fix for the problem.

**Comment by gravitystorm** [comment] 2019-03-07 10:17
This seems to be in response to https://github.com/openstreetmap/Nominatim/issues/1325

However, if we removed all the commas for search terms before sending them to nominatim, then this would break searching using commas to indicate addresses. For example, "More London" finds a commercial district called "More London", whereas "More, London" finds a shop called More in a place called London.

I believe it's common to search with commas, indicating that the part after the comma is a place, it's certainly something that I do frequently, but I'm open to other points of view. I think if removing commas from search strings was a universally good idea, then that's what nominatim itself would do.

**Comment by mmd-osm** [comment] 2019-03-07 11:29
> As noticed in this tweet this morning: https://twitter.com/TransitNinja205/status/1103301248969781248

I think that's also a duplicate of #1874, which is the root cause of this issue. Routing should be more resilient here to cater for potential Nominatim reverse lookup failures.

**Comment by lonvia** [comment] 2019-03-07 12:22
Removing commas will have a significant negative impact on the quality of the search results because it removes viable information for Nominatim to interpret the search query. Do so at your own peril.

#1874 needs to be fixed properly by removing the assumption that reverse is the opposite of forward search. Other than that, searching for names with commas is such a rare use case that such a fix is not worth the negative impact on all other search results.

**Comment by b-jazz** [comment] 2019-03-08 00:08
I see now that removing commas would be bad. How about whenever there is a comma, query nominatum twice? Once with a comma, once without, and then aggregate the results.

**Comment by lonvia** [comment] 2019-03-08 08:44
If it was viable solution, Nominatim would be doing it. In practice it means making many requests considerably slower to have a good result for that one in a million request where the comma is part of a name.

**Comment by mmd-osm** [comment] 2019-03-08 11:13
> How about whenever there is a comma, query nominatum twice? Once with a comma, once without, and then aggregate the results.

I'm not sure if you're drawing the wrong conclusions here. In the tweet you mentioned, the user _never_ entered any search term on their own (!). It was all auto-filled by the "Find directions" feature, and they simple did a right click on the map to set a from/to location on the map. That's all. Discussing if leaving out the comma would have helped here is kind of moot.

**Comment by dieterdreist** [comment] 2019-03-08 17:08
sent from a phone

> On 8. Mar 2019, at 12:13, mmd <notifications@github.com> wrote:
> 
> Discussing if leaving out the comma would have helped here is kind of moot.


would it have helped to put the name in quotes?

**Comment by mmd-osm** [comment] 2019-03-08 17:11
@dieterdreist : no, this will _not_ solve the general issue here. Please refer to @lonvia's comment above:

_#1874 needs to be fixed properly by removing the assumption that reverse is the opposite of forward search._

**Closed** 2019-03-16 15:23 UTC
