### ISSUE TITLE
Change notes to allow comments after notes are resolved

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#3570] opened 2022-06-11 05:07 UTC
### Description

I want to start the discussion on changing the way notes work right now. I can try to provide a PR at some point, but want to clarify the UX change first @gravitystorm.

### My gaol

Change the UI to motivate communication on notes after one mapper has marked them as closed. That could be, to say thank you. Or to add a piece of additional information, or to ask for clarification on something. 
However, those comments should not require the note to be reopened or worse, open-closed just for a "thank you".

The "thank you" case might sound trivial, but I think we need to look at all the places where we can make OSM more friendly and this is one.

### Current feature

1. User 1 writes a note
2. User 2 solves them, no comments possible anymore
3. User 1 wants to thank or comment again. One has to "reactivate" the note
4. … then comment
5. … then close again right after

### Proposed change

- Allow commenting always
- Use the state change of "this note is closed" as a status of the note and make it visually more visible
   - As part of the headline, this way one sees the state at a glance
   - Also as part of the timeline, this way one sees the state change as part of the discussion
     > - comment 1 (issue) 
     > - comment 2 (resolve-comment)
     > - close-info
     > - comment 3 (thank you)

### Links

- Example note https://www.openstreetmap.org/note/2532211

**Comment by HolgerJeromin** [comment] 2022-06-11 09:43
Duplicate of #864
But thanks for your thoughts on that topic!

**Comment by tomhughes** [comment] 2022-06-11 10:12
Duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/864

**Closed by tomhughes** 2022-06-11 10:12 UTC
