### ISSUE TITLE
Super-relations only render red line for way members (not relations) in search results 

### ISSUE THREAD

**Issue by dtwood** [openstreetmap/openstreetmap-website#4495] opened 2024-01-25 16:39 UTC
### URL

https://www.openstreetmap.org/relation/1657661

### How to reproduce the issue?

Visit the linked URL for the "Kungsleden (sommar)" way - I would expect to see a red line showing all components of the full Kungsleden route, but actually only the very northern two way members appear, and not any part of the route belonging to the "Etapp" relation members

### Screenshot(s) or anything else?

<img width="1509" alt="Screenshot 2024-01-25 at 16 37 11" src="https://github.com/openstreetmap/openstreetmap-website/assets/1207240/9c6933b1-88cb-4d18-8759-8de3f12a3eda">
<img width="1512" alt="Screenshot 2024-01-25 at 16 37 23" src="https://github.com/openstreetmap/openstreetmap-website/assets/1207240/4317cafb-57cd-4bfc-811f-49b873f21c41">

**Comment by tomhughes** [comment] 2024-01-25 16:59
This is basically because of the nested relations - although it uses the `/full` API endpoint that only retrieves one level of nested objects because recursing fully might take a very long time and use a huge amount of resources.

**Comment by tomhughes** [comment] 2024-01-25 17:00
Duplicate of #2772.

**Closed by tomhughes** 2024-01-25 17:00 UTC
