### ISSUE TITLE
Resolving note zooms user out to z15

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#3730] opened 2022-09-30 21:02 UTC
If you are zoomed in closer than z15, when you resolve a note the website zooms you back out to z15.

This is a bit annoying as if you have a few notes to comment upon or resolve close together in a small area, it means you need to zoom back in again to select another note rather than just click on one nearby.

Is there a particular reason for this behaviour?

**Comment by danieldegroot2** [comment] 2022-10-01 10:58
@boothym Could you provide the OS, browser and screen size you are viewing the website on, please? Could you try doing this on other devices?

For me personally (desktop), resolving a note on z>15 does not zoom out.

**Comment by boothym** [comment] 2022-10-01 19:26
Hmm, it was doing it yesterday (and in the past as well) but doesn't seem to doing it today when resolving.

Win10/Chrome/1920x1080, will keep trying to reproduce the issue, including on mobile later.

**Comment by AntonKhorev** [comment] 2022-10-09 06:18
This could happen when there's a javascript error and you get a full page reload instead of a partial reload. z15 is a default zoom for a note page.

**Comment by danieldegroot2** [comment] 2022-10-24 10:24
I've reproduced this with "comment and resolve" on https://www.openstreetmap.org/note/3411020 (Chrome 106.0.5249.119, Windows 7).

May be fixed by https://github.com/openstreetmap/openstreetmap-website/pull/3617

**Comment by AntonKhorev** [comment] 2022-10-24 10:54
I've seen something similar when pressing Hide button. And I also fixed a bug related to note hiding.

> I've reproduced this with "comment and resolve" on https://www.openstreetmap.org/note/3411020 (Chrome 106.0.5249.119, Windows 7).

Were there any js errors visible in the console?

**Comment by danieldegroot2** [comment] 2022-10-24 14:02
I didn't check. Checking again, with only selecting the note I can occasionally get the following JS error (selecting a note doesn't zoom me out, btw)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findEntry')
    at content-script.js:29:128116
    at content-script.js:29:128204
    at fS (content-script.js:29:128466)
    at qS (content-script.js:29:136329)
    at content-script.js:29:156950
(anonymous) @ content-script.js:29
(anonymous) @ content-script.js:29
fS @ content-script.js:29
qS @ content-script.js:29
(anonymous) @ content-script.js:29
Promise.then (async)
FW @ content-script.js:54
(anonymous) @ content-script.js:54
(anonymous) @ content-script.js:54
```

It doesn't look like I get any JS errors for the resolve action, but not sure.

**Comment by AntonKhorev** [comment] 2022-10-25 08:07
https://github.com/openstreetmap/openstreetmap-website/pull/3617 's error should look like this:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'text')
```
= reading a note comment text when the comment doesn't exist.

**Comment by danieldegroot2** [comment] 2023-09-22 22:43
This issue is a duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/648#issuecomment-1732102275 .

**Closed** 2023-09-24 17:32 UTC
Labels: mapview
