### ISSUE TITLE
View GPX tracks on the map

### ISSUE THREAD

**Issue by theel0ja** [openstreetmap/openstreetmap-website#1922] opened 2018-07-06 15:01 UTC
Currently, you can only view them [as GIF](https://www.openstreetmap.org/user/theel0ja/traces/2740780/picture), [on iD](https://www.openstreetmap.org/edit?gpx=2740780) or [the starting point](https://www.openstreetmap.org/?mlat=60.4903&mlon=22.183#map=14/60.4903/22.183).

I think that something like this should be implemented:
[![image](https://user-images.githubusercontent.com/5832930/42385849-9860c120-8146-11e8-97e7-934fa6315686.png)](https://theel0ja.info/leaflet-gpx-demo/?id=2740780)

[Demo](https://theel0ja.info/leaflet-gpx-demo/?id=2740780)
[Source code](https://github.com/theel0ja/leaflet-gpx-demo)

**Comment by tomhughes** [comment] 2018-07-06 15:17
Pretty sure there are already tickets requesting it.

I don't see how it fits with our goals though - you can already overlay them in the editors, where they do fulfill our goals by allowing people to add data based on a trace.

Do you have a use case in mind for showing them on the front page which assists people in editing or improving the map?

**Comment by danieldegroot2** [comment] 2023-03-19 22:44
@tomhughes [one reason](https://github.com/openstreetmap/openstreetmap-website/issues/1018#issuecomment-125320245). (also slightly less UI around the screen, easier for long traces to view directly on a map rather than satellite on low zooms/more quickly gives context of its trajectory for first assessment.)
It could also help with comparing traces and relations, though you're likely going to be in the editor already by that point. (you'd have to interact with the UI before also the relation is shown regardless.)

This issue is a duplicate of #387.

cc: @gravitystorm

**Comment by gravitystorm** [comment] 2023-03-20 09:36
Duplicate of #387

**Closed by gravitystorm** 2023-03-20 09:36 UTC
