### ISSUE TITLE
Dockerize website for new Developers

### ISSUE THREAD

**Issue by MegaMind77-coder** [openstreetmap/openstreetmap-website#3005] opened 2020-12-14 08:50 UTC
Maybe the website could be dockerized by making a docker-compose file. 
Advantages:
New developers could set up the development environment within minutes. 
Installing all dependencies would take a lot of time, using docker we none of the system dependencies would interfere with the project dev environment dependencies. Hence, a lot easier to set up a dev workspace for new developers. 
All we could run is docker-compose up to start the environment, with volumes mapped to the project. 

The project would also be a lot easier to deploy using docker.

**Comment by mmd-osm** [comment] 2020-12-14 09:03
Duplicate of #2409

**Comment by MegaMind77-coder** [comment] 2020-12-14 09:25
Oh! Looks like this issue has been well-discussed in the past.

**Closed** 2020-12-14 09:57 UTC
