### ISSUE TITLE
oauth request token url returns "500 Internal Server Error"

### ISSUE THREAD

**Issue by v-andr** [openstreetmap/openstreetmap-website#2222] opened 2019-05-07 03:49 UTC
I'm trying to log in user with osm account in my iOS app using oauth as recommended, following instructions from https://wiki.openstreetmap.org/wiki/OAuth.
But any post or get request to https://www.openstreetmap.org/oauth/request_token or https://master.apis.dev.openstreetmap.org/oauth/request_token with or without consumer key/secret results in error 500. 
UPD: I've registered another app, and it worked with new key+secret pair. 
However, I still believe it's an issue since normally such apis should have some meaningful error to notify user that some field is missing or that key has been expired

**Comment by mmd-osm** [comment] 2019-05-09 14:32
That's caused by an issue in the external library _oauth-plugin_, which is unmaintained since 2013. 

Fix is available in https://github.com/pelle/oauth-plugin/pull/143/files but that never got merged.

**Comment by tomhughes** [comment] 2019-05-09 14:57
Yes specifically this is cause by passing an invalid client key that doesn't match any known client, or possibly also a request with an invalid signature.

It's primarily a user error and while a 500 is not a good response it is as @mmd-osm says largely outside our control. I believe there are also other tickets already open for this.

**Closed by tomhughes** 2019-05-09 14:57 UTC

**Comment by mmd-osm** [comment] 2019-05-09 19:42
Right, https://github.com/openstreetmap/openstreetmap-website/issues/1049#issuecomment-136450085 concluded back in 2005: _the 500 error is a bug in an upstream library that we use_
