### ISSUE TITLE
Location issue on Edge

### ISSUE THREAD

**Issue by nikhilnayak98** [openstreetmap/openstreetmap-website#1235] opened 2016-06-11 05:37 UTC
Show my location not clickable on Microsoft edge browser.

**Comment by mmd-osm** [comment] 2019-11-05 12:32
I tried this on a recent Edge browser on Win10, and cannot reproduce it. The button is clearly visible, once I click on it, it will take me to my current location, privacy settings permitting.

I'd suggest to close this issue as not reproducible.

**Comment by gravitystorm** [comment] 2019-11-05 13:04
Thanks for testing @mmd-osm !

**Closed by gravitystorm** 2019-11-05 13:04 UTC
