### ISSUE TITLE
Some buttons have become less responsive in Safari on Mac

### ISSUE THREAD

**Issue by dankarran** [openstreetmap/openstreetmap-website#2811] opened 2020-09-05 10:06 UTC
Some time over the past couple of days, the Locate, Layers, Legend, Share and Query buttons on the map have stopped responding as reliably in Safari (13.1.2) on my Mac. The other buttons (e.g. zoom, add note) work fine, but these ones seem to require a force touch on the trackpad.

They all work fine still in Chrome.

**Comment by tomhughes** [comment] 2020-09-05 10:32
Presumably yesterday when we upgraded leaflet but there's probably not a lot we can do and certainly nothing with a report as vague as this.

**Comment by dankarran** [comment] 2020-09-05 14:21
I'll see if I can add any more detail, and/or figure out why some buttons might be behaving differently than others. I thought perhaps the custom OSM tools were behaving differently to the built-in Leaflet ones, but the 'add note' button seems fine.

**Comment by mmd-osm** [comment] 2020-09-05 14:35
iOS 13 has the same issue, when pressing the query tool button, I only see a green button for a fraction of a second but nothing else happens. I used to have intermittent issues with those buttons before, with the recent update they seem to be broken now.

**Comment by dankarran** [comment] 2020-09-05 14:58
@mmd-osm ah yeah, I see that on iOS too. Oddly, it's only the query button that has the issue on there, and the other buttons work perfectly still.

**Comment by mmd-osm** [comment] 2020-09-05 15:03
Yes, that’s exactly what I’m seeing here, too.

**Comment by dankarran** [comment] 2020-09-05 19:55
I've replicated part of the issue locally with a simple setup of Leaflet and jQuery. 

What seems to be happening is that Safari is emitting two click events for those buttons when clicking them normally, but only one event if force clicking on the trackpad. Chrome only emits one click event as expected, whether clicking normally or with force.

So the first click event in Safari is enabling the tool, and the second is disabling it straight away. That's presumably why the query button flashes green momentarily in iOS. The reason the note tool works is that pressing it a second time doesn't disable it, it just quietly loads it again.

I'll experiment with some alternatives, such as listening for 'pointerdown' instead of 'click' events (which may have unintended side effects) or listening for events using L.DomEvent instead of jQuery.

Maybe worth rolling back to the previous version of Leaflet in the meantime?

**Comment by tomhughes** [comment] 2020-09-09 13:25
Looks like this is https://github.com/Leaflet/Leaflet/pull/7260 which is now fixed upstream?

**Comment by jorisgeer** [comment] 2020-09-10 04:08
Testing Safari / Mac on a trivial javascript code : <button onclick="test"> yields a single invocation per click. It looks like a Leaflet issue.

**Comment by dankarran** [comment] 2020-09-10 10:24
It's definitely a Leaflet issue, but it looks like it will need a little more work before it's fixed.

**Comment by systemed** [comment] 2020-11-12 09:37
Could I suggest rolling back to Leaflet 1.6.0?

I realise it's a PITA and we usually track the latest Leaflet release, but osm.org is quite broken in Safari right now - no layer switcher, key, inspect features, shift-drag to zoom, share, or location, plus a couple of minor degradations (e.g. zoom transitions). https://github.com/Leaflet/Leaflet/issues/7255 is not showing any signs of immediate resolution and the 1.6.0->1.7.0 changelog doesn't otherwise seem compelling enough to justify the breakage.

**Comment by pyrog** [comment] 2020-12-29 10:50
> the Locate, Layers, Legend, Share and Query buttons on the map have stopped responding as reliably in Safari

It work only with a right-click 😞

**Comment by jorisgeer** [comment] 2021-03-21 06:21
As previous comments confirm, the issue is more serious than the title suggests. As the underlying Leaflet issue has no assignee yet since September 2020, may I suggest to roll back ? This may be a long-term issue and the benefits of 1.7.1 do not outweight the disadvantages - effectively dropping Safari / MacOS

**Comment by polarbearing** [comment] 2021-04-01 22:05
Recently my Safari upgraded from v13 to v14.0.3, and the problem is still present.

**Comment by Woastscho** [comment] 2021-07-26 12:44
Any solution yet ?

**Comment by caryhartline** [comment] 2022-02-21 19:24
For the Safari users who use a mouse reading this, if you _hold down_ the left-click for _more than a second_ when clicking on any of the affected buttons (layers, map key, etc.) then that will also work around this issue.

I will also report this issue still exists in:

Safari Version 15.3 (17612.4.9.1.8)
Safari Technology Preview Release 140 (Safari 15.4, WebKit 17614.1.1.5)
macOS 12.2.1 (21D62)

**Comment by Buggybugbug** [comment] 2022-03-03 09:08
Same here [Safari 15.3 (16612.4.9.1.8), macOS 11.6.4].
Additional workaround with trackpad: Don't tap, but press (lower trackpad section with my MacBookpro mid 2014).

**Comment by tomhughes** [comment] 2022-04-18 14:23
Leaflet 1.8.0 has now been deployed on openstreetmap.org - could somebody with Safari please check if this is still an issue?

**Comment by Andygol** [comment] 2022-04-18 17:38
@tomhughes with 1.8.0 Layers control in Safari works as expected 👍

**Comment by tomhughes** [comment] 2022-04-18 17:43
Thanks. I'll close this then!

**Closed by tomhughes** 2022-04-18 17:43 UTC
Labels: bug, awaiting upstream
