### ISSUE TITLE
OpenStreetMap.org litters my browsing history!

### ISSUE THREAD

**Issue by Openstreetmapler** [openstreetmap/openstreetmap-website#2617] opened 2020-05-08 13:44 UTC
**Every time** you **move** the map or change the **zoom,** a **new entry** in my browsing history is created, resulting in **thousands of entries** for openstreetmap.org – in fact, I already have **more than 60,000 entries!** The problem was there the whole time since I got to know OSM!
![OpenStreetMap müllt den Browserverlauf zu!](https://user-images.githubusercontent.com/9383930/81410890-c8716d80-9141-11ea-88fe-26d84dc56c11.png)
(By the way, to prevent confusion: It shows the entries of all times, not just from today, even though the today part is selected on the left.)

It would be **very appreciated** if entries were **only** created when going on the website, switching to editor mode, clicking the Permalink button etc.

**Comment by tomhughes** [comment] 2020-05-08 15:02
Duplicate of #506/

**Closed by tomhughes** 2020-05-08 15:02 UTC
