### ISSUE TITLE
Notification of changeset comment should generate a OSM message, not a normal mail

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#908] opened 2015-02-24 11:36 UTC
Currently creating a changeset comment generates a notice to the changeset creator directly via e-mail, unluckily such automated mails are prone to getting lost and depend on the destination e-mail still working in the first place. As we know from the licence change the later is not given at all.

It would be better to generate an internal message (which would trigger a mail notification to the user anyway) . If the notification is missed you still have the message count on the website and notifications in the editors to point out that you may need to act.

Further: in the current scenario "zero hour" blocks do not really work without the DWG sending a message to the user pointing out that he hasn't responded to a changeset comment.

No patch for now as the subject is likely a bit controversial.

**Comment by SomeoneElseOSM** [comment] 2015-02-24 11:49
(and something else in the same area) it would be nice if you could reply to changeset discussion comment emails the same way that you can to OSM message emails.  Would this also follow from Simon's suggestion above?

**Comment by simonpoole** [comment] 2015-02-24 11:57
Likely no, you would be replying to the noticiation message, which is not the the same as the hangeset discussion itself.

**Comment by tomhughes** [comment] 2015-02-24 12:28
Whilst it would be possible to have a new code in the reply address that marked it as a changeset comment that should be appended to the changeset discussion I would prefer not to do that for aesthetic reasons.

The problem is that emailed comments always wind up looking rather awkward/ugly and whilst it's one thing to accept that in the private context of messages I'd rather not encourage that in a public facing context like changeset comments.

**Comment by pnorman** [comment] 2015-02-24 15:55
I would like it to be easier for a user to see if there are comments on their changesets and to get notification through the website that they have had a discussion on one of their changesets. I'd also like to be able to see what changesets a different user has done that have had discussions.

I don't see that user messages would particularly solve the problem of users If they are not getting changeset discussion emails they probably won't get message emails either as they come from the same source.

There is no need for sending a private message to go along with zero hour block as the block itself can contain a message to the user directing them to the discussion they need to be involved in.

**Comment by neiljp** [comment] 2015-02-24 19:13
Could this be incorporated into a list of active/involved discussions, like how each user has a list of the notes they're involved with on their profile?

**Comment by simonpoole** [comment] 2015-03-01 09:42
@neiljp It is true that right now the notification mails are the only means to find out which discussions you've participated in and that is why them getting lost in e-mail nirvana is such a pain, but actually having a list is a different topic and I believe there is already an open issue wrt that.

**Comment by polarbearing** [comment] 2015-03-01 10:25
> actually having a list is a different topic and I believe there is already an open issue wrt that.

Yes: #842

**Comment by biswesh456** [comment] 2018-03-07 17:32
Hello, I was looking at the ideas list and came across this. Can I take this as a GSOC project. Can someone guide me if this is a project good enough for GSOC. Also since no mentors have been mentioned can I be referred to someone who can guide me for this project?

Thanks

**Comment by simonpoole** [comment] 2018-03-07 20:27
As part as a larger project to improve the messaging infrastructure on osm.org yes, stand-alone far too thin.

**Comment by biswesh456** [comment] 2018-03-07 20:40
@simonpoole Can I be guided on any specific things that are wanted in the messaging infrastructure of osm.org? I would love to contribute to it. 

Thanks

**Comment by simonpoole** [comment] 2018-03-08 09:06
https://github.com/openstreetmap/openstreetmap-website/issues/1387
https://github.com/openstreetmap/openstreetmap-website/pull/1431
and the proposed group functionality for starters.

**Comment by gravitystorm** [comment] 2019-07-03 14:01
The topic of notifications is a broad one, and one that we could definitely improve on. I would like in the future to have a system where all the various _activities_ (commenting on changesets, receiving a message, whatever) create a _notification_, and users can control how they want to receive notifications (email, instant messaging, only on the website, etc). At the moment users have no control over notifications (only via email) and there's no way to review all the notifications that you've received retrospectively.

But this specific request is for an _activity_ to trigger the creation of a _message_. I don't think that's a good approach, since it dilutes the concept of a message, and it would make it harder in the long run to create a proper notification system. So I'm closing this issue in favour of #1387

**Closed by gravitystorm** 2019-07-03 14:01 UTC
