### ISSUE TITLE
Limit allowed characters in changeset comments

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/openstreetmap-website#2501] opened 2020-01-08 22:23 UTC
Me and a few other users have been getting called out for the length of our changeset comments. While I agree we could probably shorten them, the natural tendency is to run with whatever length of rope your given. So, it would be good if the number of allowed characters was at least limited to less then what it currently is. Which would force us and other users to be more precise and focus on a single subject. As it is, even some shorter changeset comments can cover multiple things and go off topic extremely easily. Stricter limits would help IMO. 

Also, I guess one of the problems with longer comments is that it makes it hard to read them in the various changeset QA tools. Which I understand. Shorting it for that alone would be akin to mapping for rendering IMO, but its still a valid complaint. While the message length shouldn't be "Twitter short", I think there has to be good medium between that and what it currently is.

**Comment by tomhughes** [comment] 2020-01-09 00:12
I don't see any reason to limit the length and I can't imagine who has been asking you to - the problem is usually that the comment are too short, not too long!

**Comment by Adamant36** [comment] 2020-01-09 00:39
> I can't imagine who has been asking you to

@woodpeck and @SomeoneElseOSM, among others.

**Comment by gravitystorm** [comment] 2020-01-09 09:00
Can I just check - are we talking about changeset discussions or changeset tags? Confusingly, both are known as "changeset comments".

I suspect the problem with changeset discussions is that it can be a full essay in a comment. The underlying type for the `body` of a `changeset_comment` is `TEXT` and we don't specify any limits on that.

**Comment by SomeoneElseOSM** [comment] 2020-01-09 10:07
The request from me was never for a hard limit on changeset discussion comments - merely a suggestion (to a couple of contributors, actually) that they would succeed in getting their point across better if they were more succinct in what they were trying to say.

**Comment by Adamant36** [comment] 2020-01-09 10:32
> I suspect the problem with changeset discussions is that it can be a full essay in a comment.

Yeah exactly. That's the problem. 
___

@SomeoneElseOSM, I wasn't trying to say you asked for a hard limit. You did say a couple of times to write shorter messages though. Along with the request to make them more succinct, but I'm pretty sure you mentioned length also. Its possible I'm confusing your comments with another persons though. As it was more then a few people that said something about it. Limits can lead to increased succinctness though IMO. Or if not, at least its less "going off" room before a new message has to be written. Which would give people a little more breathing room before continuing. 

Also, I suspect people would be less inclined to spam the message feed with a bunch of shorter messages compared to writing one long one. If not, maybe there could be a limit on how many messages someone can send in a certain time period.

**Comment by mmd-osm** [comment] 2020-01-09 13:41
We’ve implemented a limit of 2000 characters last year!

**Comment by grischard** [comment] 2020-01-12 14:09
Downstream tools are going to have to live with the existing novels in changeset comments forever though.

**Comment by mmd-osm** [comment] 2020-02-10 21:37
Ok, so what is the final conclusion here? Do we want to introduce some limit? If not, my suggestion would be to close this issue, as there's nothing left to do.

**Comment by mmd-osm** [comment] 2024-06-22 11:05
I've created a follow up PR #4694 to introduce limits for user supplied content. Closing here.

**Closed by mmd-osm** 2024-06-22 11:05 UTC
