### ISSUE TITLE
"File not found" when saving profile changes

### ISSUE THREAD

**Issue by claudiush** [openstreetmap/openstreetmap-website#1605] opened 2017-08-02 14:46 UTC
Attempting to updated my OpenStreetMap.org profile at https://www.openstreetmap.org/user/<osm_username>/account but everytime I hit the "Save changes" button a "File not found" page is shown:
![image](https://user-images.githubusercontent.com/428616/28879235-ece01570-77a1-11e7-95d7-7dd068032d34.png)

Even not changing any profile field and just attempting to save right after entering the page gives the same error, so it seems to be independent of the changed field (I tried changing description and location)

**Comment by tomhughes** [comment] 2017-08-02 14:57
Duplicate of #1601.

**Closed by tomhughes** 2017-08-02 14:57 UTC
