### ISSUE TITLE
Add "No, don't load the data" choice

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1766] opened 2018-02-24 15:44 UTC
(User clicks [x] Show data, in a high density area.)
We see

```
Displaying 4664 features, which might slow your browser.

Are you sure you want to load the data?

    [Load the Data]
```
and no ```No, don't load the data``` button. Only an [X].

So we push the X. And.... it loads the data!

**Comment by jidanni** [comment] 2018-02-24 15:48
What's worse is now the user will have to figure out how to clear their cookies,
as they can't browse osm.org ever again without their browser getting floored.

**Comment by gravitystorm** [comment] 2018-02-26 01:35
I'm not sure why this was closed without comment - was there some discussion in a different channel that I missed?

**Comment by tomhughes** [comment] 2018-02-26 07:10
Well as far as I can tell the claimed "bug" doesn't actually happen anyway - the data does not load when the X is hit.

What does happen is that the data layer remains active and moving the map will cause a new load, with a new prompt that must again be cancelled.

Frankly we should just get rid of the data layer - it's pretty much unusable with the typical data density now in OSM and we have better tools (like the query tool) now,

**Comment by HolgerJeromin** [comment] 2018-02-26 07:18
> Well as far as I can tell the claimed "bug" doesn't actually happen anyway - the data does not load when the X is hit.

I played with it and it happened one time. (something like move, wait for popup, move, click X, data loaded)
But could not reproduce.

> Frankly we should just get rid of the data layer - it's pretty much unusable with the typical data density now in OSM and we have better tools (like the query tool) now,

yes

**Comment by gravitystorm** [comment] 2018-02-26 09:27
> Well as far as I can tell the claimed "bug" doesn't actually happen anyway - the data does not load when the X is hit.

@jidanni are you able to provide steps to reproduce this problem? I haven't managed to reproduce it either, but I suspect some combination of panning/zooming might be able to trigger this.

**Comment by dieterdreist** [comment] 2018-02-26 11:59
2018-02-26 8:10 GMT+01:00 Tom Hughes <notifications@github.com>:

> Frankly we should just get rid of the data layer - it's pretty much
> unusable with the typical data density now in OSM and we have better tools
> (like the query tool) now,



Please don't. I'm still using the data layer pretty frequently, AFAIK the
"query features" tool is only checking for certain tags, not all available
data, and you can't see geometries anyway.

FWIW, while the "query features" is nice, I'd be willing to give it up
without second thought in favor of a "show tile" (or "copy tile URL", or
"get tile info", etc.) function. It is a major annoyance that browser right
click catching has removed the "show image" functionality.

**Comment by zerebubuth** [comment] 2018-02-26 12:25
> > Frankly we should just get rid of the data layer
>
> Please don't. I'm still using the data layer pretty frequently,

Seconded. I still use the data layer, too. While the query tool is excellent and useful, there are some things which I find the data layer much better suited to.

How about moving the data layer to (and not blocking right-click on) a secondary, static site specifically for these kinds of activities? Something like `debug.openstreetmap.org`?

**Comment by tomhughes** [comment] 2018-02-26 12:31
I don't know what you mean about blocking right click?

Obviously we could move it but it doesn't solve the basic problem of it being unusable at anything less than about zoom 22 or so ;-) Plus we wouldn't even have the current safety of it querying any load with too many items - it would just kill the browser.

**Comment by zerebubuth** [comment] 2018-02-26 13:10
> I don't know what you mean about blocking right click?

The map `div` intercepts the right-click, meaning the usual browser-provided right-click menu isn't available. This was quite useful for a very small number of us who wanted a convenient way to get the tile coordinates.

> Obviously we could move it but it doesn't solve the basic problem of it being unusable at anything less than about zoom 22 or so

I was just trying to suggest a way we could preserve the current/old behaviour for the small number of us who find it useful, while the main site moves on to remove these features for the vast majority who don't. Since some of us find them useful, I though it would be nice if we could keep them around somewhere out of the way. Since neither require server-side support, we could always write our own local versions, although it would be less duplication of effort if we shared it somewhere central. And probably not onerous to host a static bunch of HTML and Javascript.

**Comment by HolgerJeromin** [comment] 2018-02-26 13:37
ref #1472 for "tile details"  view

**Comment by tomhughes** [comment] 2018-02-26 14:45
Well we could always merge my tile details branch to put that on the custom right click menu ;-) Firefox at least will still give you the browser menu with shift click as well.

**Comment by HolgerJeromin** [comment] 2018-02-26 20:46
Modern browsers have a private mode / tab which does not share cookies with the normal browser. Ideal for testing such things

**Comment by mmd-osm** [comment] 2024-06-28 13:36
Aborting the load process was again raised in #4931, so I'm closing this issue now.

**Closed by mmd-osm** 2024-06-28 13:36 UTC
