### ISSUE TITLE
pngcrush not found

### ISSUE THREAD

**Issue by dog1993** [openstreetmap/openstreetmap-website#1932] opened 2018-07-22 13:28 UTC
When I Create the databases using"bundle exec rake db:create",it reports some errors like

“pngcrush not found,please provide proper binary or disable this worker（—no--pngcrush argument or‘：pngcrush →false’ through options ）”.
“advpng not found,please provide proper binary or disable this worker（—no--advpng argument or‘：advpng →false’ through options） ”.

It seems that these errors are related to image.Does the file "openstreetmap-website" on  https://github.com/openstreetmap/openstreetmap-website.git     lack some useful  things?How can I fit it？

**Comment by tomhughes** [comment] 2018-07-22 13:38
Duplicate of #1931.

**Closed by tomhughes** 2018-07-22 13:38 UTC
