### ISSUE TITLE
White grid around map tiles when page zoom set to 33%, 67%, 80%, 85%, 90% or 115% 

### ISSUE THREAD

**Issue by verhovsky** [openstreetmap/openstreetmap-website#5109] opened 2024-08-22 21:52 UTC
1. Open https://www.openstreetmap.org
2. Press Cmd+- (or ctrl+- on Windows/Linux I think) to set the browser's Page Zoom to 90%

<img width="866" alt="Screenshot 2024-08-22 at 14 42 18" src="https://github.com/user-attachments/assets/7eff17a1-4f9d-40c4-a766-0fdb6b965cce">

I see this grid at 33%, 67%, 80% and 90% zoom but not at 25%, 50% or 100% or more. At 75% zoom I see only a horizontal grid

<img width="739" alt="Screenshot 2024-08-22 at 14 43 21" src="https://github.com/user-attachments/assets/5f4549dd-a9e3-4b2d-9adf-67cb8d42aa94">

Chrome 127.0.6533.120, macOS 14.6.1, 2020 MacBook Air M1 with a 13.3-inch (2560 × 1600) display. On Safari I see it at 85% and 115% zoom, no others. I don't see the issue on Firefox at any zoom level.

**Comment by tomhughes** [comment] 2024-08-22 23:11
Well yes if you do weird zooms you may provoke rounding errors so it's probably not that surprising.

It's certainly not something we can do anything about here anyway, it's something that would have to be resolved in [Leaflet](https://github.com/Leaflet/Leaflet).

**Comment by tomhughes** [comment] 2024-08-22 23:12
https://github.com/Leaflet/Leaflet/issues/9399 is probably relevant.

**Closed by tomhughes** 2024-08-22 23:11 UTC

**Comment by verhovsky** [comment] 2024-08-22 23:41
your first sentence is entirely unnecessary

**Comment by mmd-osm** [comment] 2024-08-23 07:47
https://github.com/Leaflet/Leaflet/issues/3575 has a fairly long list of what other folks have tried out to get rid of white lines.

**Comment by Nekzuris** [comment] 2024-12-14 22:02
@verhovsky How did you set specific zoom values like 85% and 115%?
I found that this white grid can simply be removed with CSS exceptions for specific pixel ratios (see https://github.com/Leaflet/Leaflet/pull/9560) but I was only able to test for these values https://github.com/openstreetmap/iD/pull/10594#issuecomment-2540006158.

**Comment by verhovsky** [comment] 2024-12-16 14:39
@Nekzuris they're just zoom levels on Safari.

<img width="511" alt="Screenshot 2024-12-16 at 07 38 10" src="https://github.com/user-attachments/assets/bcd41dd3-46dc-4478-942f-611e189cb406" />

**Comment by Nekzuris** [comment] 2024-12-16 20:22
Okay, I don’t have a Mac to test with Safari, but I found an extension to precisely change zoom levels on Chrome and it looks like _mix-blend-mode: plus-lighter_ creates problems more often than not, so it should only be applied to specific pixel ratios where it’s been confirmed to work.
