### ISSUE TITLE
Add notifcations functionality

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#3498] opened 2022-03-12 10:53 UTC
### Description

It can be based on messages where if the sender_id is 0, it can be hidden from the messages inbox and shown in the notification's inbox. That way you won't have to add new tables to the DB. Notifications can be received for the same things that user's receive emails (notes, changeset comments, somebody friended them etc.).

**Comment by tomhughes** [comment] 2022-03-12 11:01
Duplicate of #1387.

**Closed by tomhughes** 2022-03-12 11:01 UTC
