### ISSUE TITLE
500 error for a specific note

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#2658] opened 2020-06-13 23:59 UTC
https://www.openstreetmap.org/note/1946853 found via http://resultmaps.neis-one.org/osm-notes-country?c=Equatorial%20Guinea

>Application error

>The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

>Feel free to contact the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.

>This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)

Not sure is it some bug, unclear result of note moderated away, coincidence or something else

**Comment by tomhughes** [comment] 2020-06-14 07:16
Probably a duplicate of #2146.

**Comment by tomhughes** [comment] 2020-06-14 07:18
Confirmed - there is only one comment and it is by a user that has closed their account.

**Closed by tomhughes** 2020-06-14 07:18 UTC
