### ISSUE TITLE
Select language more easily

### ISSUE THREAD

**Issue by IVAN-RSM** [openstreetmap/openstreetmap-website#2114] opened 2019-01-13 12:30 UTC
Currently, to change the language of the anonymous user interface, you must change the language of the browser and with registered user you have to write in the settings of your language.
This is not easy, and presents the following problems:
-Not all browsers have all the languages ​​that Osm has.
-Not all users know what is the code of their language to write in the settings and thus have their language.
-There are people who prefer a different language to the one they have in their system, whether they are a user or not.

Has easy solution:
-Put a drop-down button to select language in the interface itself, whether or not you are a registered user, to encourage the use of your language!

**Comment by mmd-osm** [comment] 2019-01-13 12:33
That's a duplicate of #1115

**Closed** 2019-01-13 12:38 UTC

**Comment by IVAN-RSM** [comment] 2019-01-13 12:49
.

**Comment by IVAN-RSM** [comment] 2019-01-13 12:50
I hope you have it in mind and do not close without more
