### ISSUE TITLE
No way to change the interface language unless one is logged in or tinkers with browser's preferred language

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1940] opened 2018-07-26 07:25 UTC
No way to change the interface language unless one is logged in.
Forced to tinker with the browser's settings -- no language selector on the pages.
Some people do not wish to change their browser's settings... affecting more than just this website.

**Comment by jidanni** [comment] 2018-07-26 07:38
https://www.bing.com/maps has the language selector at the top right.

**Comment by SomeoneElseOSM** [comment] 2018-07-26 07:39
Whilst i susoect it'd be a pretty niche requirement I'd certainly find this useful. With a DWG hat on I often need to communicate with other mappers in a language that is not one that I see the osm.org website in, and it'd be really useful sometimes to see what words OSM uses for things.

**Comment by tomhughes** [comment] 2018-07-26 07:40
I'm pretty sure there are already tickets for this. I even have a branch but we never really got a UI that worked without taking up lots of space.

**Comment by jidanni** [comment] 2018-07-26 07:40
https://www.google.com/maps/ has the language selector in the menu at upper left.

**Comment by tomhughes** [comment] 2018-07-26 07:41
https://github.com/tomhughes/openstreetmap-website/tree/locale is my branch.

**Comment by gravitystorm** [comment] 2018-08-29 02:09
Duplicate of #1115

**Closed by gravitystorm** 2018-08-29 02:09 UTC
