### ISSUE TITLE
The border on navbar buttons has become larger

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#4263] opened 2023-09-28 18:37 UTC
### URL

https://www.openstreetmap.org

### How to reproduce the issue?

The border is now thicker, earlier today it was thinner.

### Screenshot(s) or anything else?

Screenshot from time of writing:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/19364673/edf78fcd-528e-4a34-9ebc-8c2f3fbb9409)

Screenshot from a tab that is open since this morning (and hasn't been refreshed since)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/19364673/47ec2ed1-ed30-41ac-8d62-423f4c5656ea)

**Comment by Dimitar5555** [comment] 2023-09-28 19:09
It is the first thing that catches my eye when I look at the screen (specifically middle left part where most of the editing happens in iD). I wouldn't call it a problem but it's annoying.

**Comment by tomhughes** [comment] 2023-09-28 19:25
I just assumed it was expected but it does look like it's an error. The root cause is https://github.com/openstreetmap/openstreetmap-website/blob/32ffd66eb5cb888b47446ae5053ab57f8a1e83cf/app/assets/stylesheets/parameters.scss#L32 which @gravitystorm said was copied from bootstrap but bootstrap actually has it as one pixel not two.

**Comment by tomhughes** [comment] 2023-09-28 19:26
The same is true with the radius on the next line which is actually `.25rem` in the bootstrap stylesheet.

**Comment by gravitystorm** [comment] 2023-09-28 19:51
Oh phooey, those were values I was using for debugging - I've copied the wrong ones into the PR.

Either they can be fixed immediately by updating parameters.scss, or alternatively #4261 can be merged, which upgrades to 5.2 and removes these overrides entirely.

**Comment by gravitystorm** [comment] 2023-09-28 19:54
> Yes, we've upgraded bootstrap to 5.1 which comes with some style changes.

We've been using 5.1 for a long time, [the recent PR](https://github.com/openstreetmap/openstreetmap-website/pull/4260) switched the scss compilation engine without changing bootstrap version. But that PR included the wrong values for these two settings, as part of a workaround for a different issue. I didn't notice because I was focussed on viewing the 5.2 and 5.3 PRs to check for any visual changes in those PRs.

**Closed** 2023-09-28 20:16 UTC
