### ISSUE TITLE
Node history: add marker to location links

### ISSUE THREAD

**Issue by scaidermern** [openstreetmap/openstreetmap-website#663] opened 2013-12-19 12:57 UTC
When viewing the history of a node there is a 'Location:' link for every entry which opens the corresponding location on the map. Unfortunately there is no marker set. This makes identifying the exact position really hard.

**Comment by mmd-osm** [comment] 2024-06-25 17:51
Closing, duplicate of #576

**Closed by mmd-osm** 2024-06-25 17:51 UTC
