### ISSUE TITLE
Bug with "empty" Notes

### ISSUE THREAD

**Issue by fidoez** [openstreetmap/openstreetmap-website#3168] opened 2021-04-09 12:48 UTC
Some existing, not closed OSM-notes lose their information, i.e. they still exist, but have no information/comments. Some days before they have had comments. I call them "empty" notes.

I know today 3 such notes with IDs: 730590, 1718681, 2017046
A http-request to these notes delivers a server error (500): https://www.openstreetmap.org/note/730590
OsmAnd and JOSM show these notes. I didn't try to close them to preserve them.
The API https://api.openstreetmap.org/api/0.6/notes?bbox=7.63,50.89,7.64,50.90&closed=0 results in such an empty note (s. File2.txt). 4 weeks before the API results in File1.txt
It has to be examined:
1. Which app/process destroys the notes (produces empty notes)
2. Prevent the database to accept empty notes
3. Find a way to delete all existing empty notes, when step 2. is done

[File1.txt](https://github.com/openstreetmap/openstreetmap-website/files/6285739/File1.txt)
[File2.txt](https://github.com/openstreetmap/openstreetmap-website/files/6285741/File2.txt)

**Comment by tomhughes** [comment] 2021-04-09 13:10
Duplicate of #2146.

**Closed by tomhughes** 2021-04-09 13:10 UTC
