### ISSUE TITLE
In node/way/relation details, brand:wikipedia & operator:wikipedia values should be links

### ISSUE THREAD

**Issue by tguen** [openstreetmap/openstreetmap-website#3685] opened 2022-09-11 08:07 UTC
The values of `wikidata`, `brand:wikidata`, `operator:wikidata`, `network:wikidata` are all links to wikidata.org, while values of `wikipedia` link to wikipedia.org but values of `brand:wikipedia`, `operator:wikipedia`, `network:wikipedia` do not. I would like these to all become links.

Example: https://www.openstreetmap.org/way/130673563

**Comment by tomhughes** [comment] 2022-09-11 09:59
Duplicate of #2184.

**Closed by tomhughes** 2022-09-11 09:59 UTC
