### ISSUE TITLE
History navigation inconsistent  

### ISSUE THREAD

**Issue by wireguy** [openstreetmap/openstreetmap-website#4506] opened 2024-02-03 14:40 UTC
### URL

https://www.openstreetmap.org/relation/1941310

### How to reproduce the issue?

going to: [https://www.openstreetmap.org/relation/1941310](https://www.openstreetmap.org/relation/1941310)
shows the latest version of the relation, 5, but the history navigation has the previous version as 1, and the next version as 5:

<img width="237" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/47227325/6ec52a9d-0812-4d0d-b8c8-fcbf673a3a1b">

going to [https://www.openstreetmap.org/relation/1941310/history/5](https://www.openstreetmap.org/relation/1941310/history/5)
also shows version 5 of the relation, but the history navigation has the previous version as 4, and no next version

<img width="232" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/47227325/81f5b3e9-3f9e-4640-93ee-bea7b6d24e0f">

The second way seems correct, from version 5, the previous should be version 4.

### Screenshot(s) or anything else?

issue seems to be in:

[app/views/browse/feature.html.erb](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/browse/feature.html.erb)

**Comment by tomhughes** [comment] 2024-02-03 15:07
That is the intended behaviour - the "current" version view doesn't have next/previous version buttons because that would make no sense. Instead it has first/last buttons which take you into the history view and there you have next/previous buttons.

It's not ideal that the icons are the same but I don't have any better ideas either...

**Comment by wireguy** [comment] 2024-02-03 15:31
ideas:

<img width="156" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/47227325/fdfbbafe-7e7c-43fc-ac2d-c2dd953a469e">

or just simple text 

<<   <   5  >  >>
|<    <  5  >   >|

<< or  |< go to the first
< go to the previous

**Comment by AntonKhorev** [comment] 2024-02-09 12:38
I plan to have < > icons for previous/next versions and << >> for first/last. That's why I started doing svg icons that are currently on diaries/traces pages.

**Comment by tomhughes** [comment] 2024-02-25 09:41
I believe this has now been resolved by #4513.

**Closed by tomhughes** 2024-02-25 09:41 UTC
