### ISSUE TITLE
Various buttons do not work on MacOS Safari browser

### ISSUE THREAD

**Issue by nitramwin** [openstreetmap/openstreetmap-website#3260] opened 2021-07-19 14:51 UTC
On MacOS's Safari browser, the following buttons don't seem to work for me since over a year. These are the buttons:

- Layers
- Map Key
- Share
- Query features

**Comment by tomhughes** [comment] 2021-07-19 14:59
Duplicate of #2811.

**Closed by tomhughes** 2021-07-19 14:59 UTC
