### ISSUE TITLE
Atom feed on user's edit history is broken

### ISSUE THREAD

**Issue by nachanon** [openstreetmap/openstreetmap-website#2331] opened 2019-07-27 13:48 UTC
Back when I was investigating [this improper MAPS.ME contributions](https://forum.openstreetmap.org/viewtopic.php?id=64515), I tried to use an Atom feed shown on browser's location bar while viewing [user's edit history page](https://www.openstreetmap.org/user/hs4rtu/history) to keep track of any additional edit at the time; but **clicking on the feed icon gave a HTTP 404 error instead of a functional feed**.

Exact steps to reproduce:

- Start a browser with JavaScript enabled.
- Go to [user `hs4rtu`'s history page](https://www.openstreetmap.org/user/hs4rtu/history) on OpenStreetMap.
- The browser would show user's edit list and zoom to the area of most-latest edits by that user. ([Screenshot](https://u.cubeupload.com/xwindows/1ym9fS.png))
- Click on the feed icon at the end of address bar.
- Instead of displaying feed, the browser would take you to [a URL with gibberish Ruby-like hashtable string](https://www.openstreetmap.org/user/hs4rtu/{%22display_name%22=%3E%22hs4rtu%22,%20%22max_id%22=%3Enil,%20%22xhr%22=%3Enil,%20%22action%22=%3E:feed}?bbox=undefined), which gives 404 _File not found_ error:
	
	![](https://u.cubeupload.com/xwindows/nuFIKd.png)
	
	Caveat: If your browser does not show the 404 page, see _Notes_ below (point 3).

Browser: Opera 11.64  
System: Microsoft Windows XP SP3

-----

### Notes ###

1. **I'm quite sure that Atom feed of area-based history is also affected.**
1. Enabling or disabling JavaScript does not matter.
1. This is not browser-specific, a test under Pale Moon 25.5.0 on the same machine yields essentially the same result (non-functional feed), though the symptom is more subtle...
	
	Under this browser, clicking feed icon would make the browser appear to load something, and when the loading finished, nothing happens: the browser is still in the unchanged history page with unchanged URL. A peek with browser's _Inspect_ tool reveals this code inside `<head>` element:
	
	![](https://u.cubeupload.com/xwindows/UYeyC6.png)
	
	Right-clicking the `<link>` tag and select <q>Copy outer HTML</q>, gives the following HTML code:
		
		<link rel="alternate" type="application/atom+xml" title="ATOM" href="{&quot;display_name&quot;=>&quot;hs4rtu&quot;, &quot;max_id&quot;=>nil, &quot;xhr&quot;=>nil, &quot;action&quot;=>:feed}?bbox=undefined">
	
	**The feed's URL is effectively the same as one in Opera's result.** Note that viewing the element's code before or after clicking the feed icon does not make any difference.

**Comment by gravitystorm** [comment] 2019-07-28 14:00
Thanks @nachanon, I have verified this. 

I think the root cause is that we're [passing @params to the link helper](https://github.com/openstreetmap/openstreetmap-website/blob/02e5a93dc529c491afafa76b281238463ac0afc5/app/views/changesets/history.html.erb#L3) instead of a plain hash, and something is blowing up when that happens. But I haven't tested that hypothesis.

**Comment by mmd-osm** [comment] 2019-08-02 08:57
You can also use https://www.openstreetmap.org/user/hs4rtu/history/feed for the time being.

**Comment by AntonKhorev** [comment] 2022-09-14 22:36
This was mostly fixed in https://github.com/openstreetmap/openstreetmap-website/commit/e430bc0f7f90d2765aa0218093e518d21b9173b1 (#3085) except for `?bbox=undefined`.

`?bbox=undefined` was fixed in #3680.

**Closed** 2022-09-14 22:53 UTC
