### ISSUE TITLE
"Where am I?" feature returns address of the center of the map instead of show user location via HTML5 API

### ISSUE THREAD

**Issue by Rezonansowy** [openstreetmap/openstreetmap-website#880] opened 2015-01-28 13:29 UTC
It should return the client location via HTML5 GeoLocation API.
Doc: http://www.w3.org/TR/geolocation-API/
Demo: http://html5demos.com/geo

**Comment by danstowell** [comment] 2015-01-28 13:33
This is because the link is badly labeled! It doesn't mean what you think it means :( - see #412

(This is a recurring theme. Also reported in #815. The repeated raising of this issue might motivate a change?)

**Comment by Rezonansowy** [comment] 2015-01-28 13:41
@danstowell But this feature has no sense otherwise. "where is my map positioned" doesn't seem to be very useful and the real "Where am I?" which tells me my location – so I don't have to search it – is really wanted, useful (not only for users) and standard in digital map viewing.

**Comment by tomhughes** [comment] 2015-01-28 14:43
Well "where is my map positioned" is exactly what it was added for - people who were sent a link to a zoomed in map and wanted to know what part of the world they were looking at.

As @dankarran says, this is a dupe of #815 anyway.

**Closed by tomhughes** 2015-01-28 14:43 UTC
