### ISSUE TITLE
Allow to see which edits were made by a specific deleted account

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#3667] opened 2022-08-30 05:41 UTC
Stronger version of #3585

https://www.openstreetmap.org/user/NotRedArroyo is a now deleted vandal account ( https://www.openstreetmap.org/user_blocks/6291 )

One of destructive edits was https://www.openstreetmap.org/changeset/125332878 but now it is impossible to track down other that should be reverted

**Comment by mmd-osm** [comment] 2022-08-30 08:49
Try this one for a list of all changesets by that user: https://api.openstreetmap.org/api/0.6/changesets.json?user=16519504

**Comment by mmd-osm** [comment] 2022-08-30 18:17
Adding a few screenshots how this looks like in JOSM's Changeset Manager:


![cs1](https://user-images.githubusercontent.com/5842757/187513014-94666e35-3c27-414c-84cc-a2753a1a7a64.png)

![cs2](https://user-images.githubusercontent.com/5842757/187513031-81a80225-3a38-4f81-a2ad-d66b583a0e98.png)

**Comment by danieldegroot2** [comment] 2022-11-04 23:56
Duplicate of #1311

**Closed** 2022-11-05 06:51 UTC
