### ISSUE TITLE
  GPS trace not displayed in "Map" mode: bug or feature?

### ISSUE THREAD

**Issue by bagage** [openstreetmap/openstreetmap-website#1018] opened 2015-07-27 19:08 UTC
If I go in top-right menu ["GPS Traces"](http://www.openstreetmap.org/traces) and select "map" option near a trace (for instance using [this one](http://www.openstreetmap.org/#map=14/44.9002/5.55638)), my map is centered on the GPS trace bounding box, but the trace itself is not displayed. 

If I select "edit" instead of "map", iD editor is launched and the trace is displayed in pink. It seems that these 2 options do not use the same API to display the GPS trace so I guess the issue is elsewhere?

I thought it was an issue with visibility of the trace so I tried a public GPS trace (link above) but it seems that there are no differences. Same behavior on 2 computers running Iceweasel/Firefox (Debian), Chromium/Chrome (Debian) and also Firefox (Windows).

**Comment by bagage** [comment] 2015-07-27 19:11
According to #387 this is a duplicate of [this](https://trac.openstreetmap.org/ticket/2276) but should the website not be modified to remove the "Map" option if it does not what we would expect it to do (eg display the GPS trace)?

**Comment by tomhughes** [comment] 2015-07-27 19:26
I don't understand what you're saying... You talk about the `more` option, which displays the detail page for a trace, but that you start talking about a map box. What exactly is this map box?

In your second comment it seems that you're asking to be able to display the trace on the map, but I don't understand how we get there from your original problem description...

**Comment by tomhughes** [comment] 2015-07-27 19:26
Oh, and it's the "iD editor" not "openID".

**Comment by bagage** [comment] 2015-07-27 19:29
My bad, fixed various typos in initial post.

**Comment by tomhughes** [comment] 2015-07-27 19:31
So I guess you are saying that the "map" link on the "more" page does not display the trace overlaid on the map. That's correct, but it's not a bug, because it was never intended to. It just displays the map in the area of the trace. The "edit" link, which is a more recent addition, shows the trace in an editor so you can draw the features it represents.

There's no obvious use case for display a trace on the map without edit support - just displaying it is not really a valid use case for the site because the goal of the site is to support entering data into the main database not to provide a way for people to display traces to the world.

In any case as you correctly discovered, this is a duplicate of #387.

**Closed by tomhughes** 2015-07-27 19:31 UTC

**Comment by bagage** [comment] 2015-07-27 19:36
Yes I know that but there is at least one use case: display the trace to ensure that the track is mapped before entering edit mode and start really mapping it. 
Why not using edit mode directly? Because this is much more slower to open iD editor than just standard view, and everything is drawn (including buildings, etc.) while I only want to ensure that routes are present.

**Comment by bhousel** [comment] 2015-07-27 19:36
@tomhughes  yes, this link:

![screenshot 2015-07-27 15 29 16](https://cloud.githubusercontent.com/assets/38784/8915727/b862e042-3474-11e5-9594-6ca3e4971d29.png)

re: openstreetmap/iD#2741

**Comment by tomhughes** [comment] 2015-07-27 21:37
@bagage I'm not saying we'd refuse to implement it, but the trac ticket has been open for six years and so far nobody has been interested enough to write a patch.

**Comment by bagage** [comment] 2015-07-30 16:39
Yes I see. Many progresses have been made in 6 years and I guess that navigation routing could help on this matter: it also draws line, is not it? Sure this is done client-side and to do a similar solution this would require to download the GPX trace first.. 
Anyway I am not a web developer and will not be able to patch this, so I will only stop use that option now that I know what it does and what it does not.

Thanks for the clarifications.
