### ISSUE TITLE
Allow notes to be moved

### ISSUE THREAD

**Issue by sjvudp** [openstreetmap/openstreetmap-website#4815] opened 2024-05-18 22:41 UTC
### Problem

StreetComplete is renowned for placing notes at the wrong locations, sometime 100 meters off.
When I tried to re-locate a mis-placed note using the iD editor, I failed doing this:
* Click on the note marker to highlight it
* Press "m" for "move"
* Move the mouse, hoping the note marker would move

Well, you cannot re-locate a note like that, but I think it would be nice if it would work like that.
When implementing, an automatic comment could be added stating who relocated the note, and maybe also the positions being involved (i.e. specifically the old one).

### Description

Add an easy (obvious) way allowing to re-locate a misplaced note.

### Screenshots

![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/6734808/c4a410de-1d6b-4aee-a3b1-7790bc0bbfbb)

**Comment by tomhughes** [comment] 2024-05-18 22:59
This is nothing to do with the editor - moving notes is not something that is supported and I'm not sure it's a reasonable thing to allow except possibly for the person that originally opened it. I don't think it would be appropriate for other people to try and guess what the original reporter intended and move it.

**Comment by sjvudp** [comment] 2024-05-18 23:03
As I also saw the danger of mis-use, I suggested to record the original position. Thus one could "undo" the move. Also (with some logic) hovering over the old position in the comment could show it on the map (if it's nearby).

**Comment by matkoniecz** [comment] 2024-05-20 11:33
> StreetComplete is renowned for placing notes at the wrong locations, sometime 100 meters off.

[citation needed]

See https://github.com/streetcomplete/StreetComplete/issues/5581 for details. In particular, noone so far managed to record process leading to this. Currently issue is closed as user error or device-specific issues is considered as most likely.

**Comment by danieldegroot2** [comment] 2024-05-20 11:50
Related osm.org-specific (for notes created/viewed on osm.org itself):<br/>#2588,<br/>#395 (already included in StreetComplete itself),<br/>#776/#2303,<br/>#667/#4400,<br/>#1849 (edit/delete note comments -may or may not include editing original note's text-, instead of closing/hiding whole note),<br/>#385 (for notes which are at wrong location due to outdated third-party application, currently already provided by StreetComplete itself)

Editors furthermore have existing issues for bugs creating overlapping/duplicate notes.

**Comment by mmd-osm** [comment] 2024-06-23 20:46
For context: this seems to be an attempt to work around issues that @sjvudp experienced when creating notes in StreetComplete. Other users apparently were unable to reproduce the issue. Maybe some device specific issue (?).

**Comment by matkoniecz** [comment] 2024-06-24 00:42
or maybe user error? I suspected that they missed that note will be placed at location shown on map, not on current GPS coordinates

**Comment by mmd-osm** [comment] 2024-06-24 16:04
Yes, they could do some more checks to identify the root cause of the issue. For now I'm going to close the issue, since nobody else was facing a similar issue. Feel free to report back on any new findings.

**Closed** 2024-06-24 16:04 UTC
Labels: notes
