### ISSUE TITLE
welcome banner close button (x) hidden behind text

### ISSUE THREAD

**Issue by fgnievinski** [openstreetmap/openstreetmap-website#2850] opened 2020-09-25 17:23 UTC
![Clipboard03](https://user-images.githubusercontent.com/5018500/94297255-99199c80-ff3a-11ea-936d-0988478328e0.png)

my screen size/resolution is 1280x720

Chrome on Windows 10

**Comment by mmd-osm** [comment] 2020-09-26 12:36
Duplicate of #2530

**Closed** 2020-10-21 20:13 UTC
