### ISSUE TITLE
Diary posts should populate Open Graph tags for social sharing

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/openstreetmap-website#1361] opened 2016-11-08 14:39 UTC
It makes me sad when I try to share a diary post on a social site like Facebook or Twitter, and the site can't automatically fetch the title and highlight image because we don't set the necessary Open Graph tags.

Open Graph debug tool here:
https://developers.facebook.com/tools/debug/sharing/

For example, if I try to share this post:
https://www.openstreetmap.org/user/PlaneMad/diary/39846

I will end up with a generic share item with no image, and the description just talks about OpenStreetMap, not a description of the post that I am trying to share:

<img width="600" alt="screenshot 2016-11-08 09 35 28" src="https://cloud.githubusercontent.com/assets/38784/20103128/b7dfc646-a596-11e6-84cd-565d334a5dcd.png">

**Comment by tomhughes** [comment] 2016-11-08 16:08
Is this not a duplicate of #739?

**Comment by tomhughes** [comment] 2016-11-08 16:09
We seem to be passing the diary entry title, and I'm not sure how we could pass an image - even if we could find the images (which would be hard) how would we choose which one if there was more than one?

**Comment by bhousel** [comment] 2016-11-08 16:19
I'm considering #739 as sharing for map links and #1361 as sharing for diary links. 

> We seem to be passing the diary entry title, and I'm not sure how we could pass an image - even if we could find the images (which would be hard) how would we choose which one if there was more than one?

Maybe just the first image?  It's better than nothing.   

Yes, I agree this is a hard problem.  Honestly I don't really think we should have diaries in OpenStreetMap.  We should instead focus our limited developer attention on making the best map possible.   But if we _are_ going to embed a barebones blogging engine, we need to at least make the content socially shareable.

How would you feel about splitting the diary code out into a separate repository?

**Comment by tomhughes** [comment] 2016-11-08 19:04
I agree that we probably shouldn't have added the diaries in the first place, but it's hard to go back on that now...

I'm not quite sure how you thinking splitting them out would work/help? Do you mean we would run them as a separate service? That they would somehow be pulled back into the existing code? Bearing in mind we have outstanding code to pull them into a moderation system which would likely increase the level of integration...

**Comment by simonpoole** [comment] 2016-11-08 23:52
@bhousel while naturally every extra feature is a bit of a pain with our development model, the user diaries are for all practical purposes the only way an OSM contributor can reach a larger part of the community in a reasonably light weight way. 

The alternative boils down to running you own blog somewhere, then making it popular enough that it gets included in the blogs.openstreetmap.org feed, where it just might get some exposure to the community in the end. A rather large hurdle to get over if you just want to tell your fellow mappers a bit about what you are currently mapping. 

Now while it would be nice to be able to reasonably share diary entries outside of OSM, not being able to do so doesn't impact the core functionality of sharing your thoughts with other OSMers.

**Comment by bhousel** [comment] 2016-11-09 00:20
From @simonpoole:
>while naturally every extra feature is a bit of a pain with our development model, the user diaries are for all practical purposes the only way an OSM contributor can reach a larger part of the community in a reasonably light weight way. 

To be clear, I'm not saying we should get rid of diaries.  We have them and people use them, so we might as well keep them. 


From @tomhughes:
> I'm not quite sure how you thinking splitting them out would work/help? Do you mean we would run them as a separate service?

It makes more sense to me as a totally separate project from the main website, but I haven't looked into the code so there could be deeper connections between the diaries and the rest of the website that I don't know about.

**Comment by zerebubuth** [comment] 2016-11-09 11:20
> [Diary entries] makes more sense to me as a totally separate project from the main website, but I haven't looked into the code so there could be deeper connections between the diaries and the rest of the website that I don't know about.

I think the biggest connection is the users table. We'd need to share that information and sessions between the different projects to make it still seem like one whole "site". This is something that's been on my TODO list for a few years (see [What to Do? step 6](http://www.asklater.com/matt/blog/2015/11/18/the-road-to-api-07/)), and I'm very sad that I have only just crossed step 1 off that list, almost a year later.

@bhousel I would love to help do this. What could we start doing?

@gravitystorm does this overlap with the [devise](https://github.com/plataformatec/devise) stuff you were talking about before? Would that be helpfully combined with this, or would it be a distraction?

**Comment by tomhughes** [comment] 2016-11-09 11:22
The users table is the biggest connection right now, but if we ever get the moderation queue sorted out that that creates a single point where all moderations reports (whether the report is against a diary entry, a diary comment, a user or whatever) are held in a single queue.

**Comment by bhousel** [comment] 2016-11-09 14:32
Good ideas @zerebubuth & @tomhughes, thanks! 
Could a hypothetical `openstreetmap-diaries` app just use OAuth via [osm-auth lib](https://github.com/osmlab/osm-auth) against the main site when people want to post or comment?  Then it wouldn't need the full users table.  It would still need something like a `diary-users` table that just contains user details to link to posts/comments.

We've gone pretty far off topic from the original ticket, so I'm going to rename this and open a new one for _just_ the opengraph stuff.

**Comment by tomhughes** [comment] 2016-11-09 14:34
Surely it makes more sense to leave this and open a new one for the idea of separating the diaries?

**Comment by bhousel** [comment] 2016-11-09 14:34
> Surely it makes more sense to leave this and open a new one for the idea of separating the diaries?

yes you are right hehe

**Comment by mmd-osm** [comment] 2024-08-01 21:22
Some of the requirements in this issue seem to be covered by #4882 in the meantime. Is there anything left to do here, or can we close this one?

**Comment by AntonKhorev** [comment] 2024-08-02 15:54
> Is there anything left to do here

`og:description` of course

**Closed** 2024-08-14 13:38 UTC
Labels: diaries

**Comment by talllguy** [comment] 2024-08-15 01:52
Looks great! ![image](https://github.com/user-attachments/assets/1a0b88eb-6a58-4960-8124-f2939d5acb16)
