### ISSUE TITLE
bundle exec rake yarn:install - Error

### ISSUE THREAD

**Issue by basilstr** [openstreetmap/openstreetmap-website#3013] opened 2020-12-20 18:01 UTC
I try install openstreetmap-website.
In the following command:
bundle exec rake yarn:install

![screen](https://user-images.githubusercontent.com/61964340/102720397-bf15c980-42fc-11eb-9935-2aaebf4b88eb.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/61964340/102720405-cc32b880-42fc-11eb-888d-060c9d04e317.jpg)

I used recommendation tomhughes
sudo apt-get install npm
sudo npm install -g yarn
But the result remained the same

My system is hosted on VirtualBox Version 6.1.16 r140961 (Qt5.6.2) (windows)
![Screenshot_2](https://user-images.githubusercontent.com/61964340/102720486-52e79580-42fd-11eb-920c-c7d17e7245fe.jpg)

Description:	Ubuntu 20.04.1 LTS
Release:	20.04

What am I doing wrong?

**Comment by RogierB** [comment] 2020-12-21 12:34
I've got the same problem.
I'm running Ubuntu 20.04 on Windows 10 in WSL.

**Comment by mmd-osm** [comment] 2020-12-21 12:37
Error message looks very similar to: https://bugs.launchpad.net/ubuntu/+source/ruby-thor/+bug/1885424

**Comment by RogierB** [comment] 2020-12-21 12:58
I can confirm that adding the 'gem 'thor', '~> 0.20.3'' to the GemFile does fix the problem.
My knowledge with ruby, bundle, yarn and the likes is limited but i do understand that this is a way older version than what OSM is supposed to be using. I also got a message that i went back to an older version when running this "fix"

**Comment by tuckerrc** [comment] 2020-12-21 14:32
It looks like you are using the system ruby and gems. Is there any reason you didn't use rbenv? I'm not very familiar with WSL but I assume you can install rbenv and ruby the same way you would on a regular Ubuntu install.

**Comment by gravitystorm** [comment] 2020-12-21 14:41
> Is there any reason you didn't use rbenv? I'm not very familiar with WSL but I assume you can install rbenv and ruby the same way you would on a regular Ubuntu install.

* We don't recommend rbenv. Contributors are free to use it if they want, but we don't offer any support or encouragement to do so.
* They are using Virtualbox, not WSL

**Comment by tuckerrc** [comment] 2020-12-21 14:48
Sorry, I saw the "optional" instructions for rbenv in the INSTALL.md and that is what I used. I won't recommend it again.

I mixed up the issue opener with a commenter about WSL. (I guess I'm still a little new)

**Comment by gravitystorm** [comment] 2020-12-21 14:49
> Sorry, I saw the "optional" instructions for rbenv in the INSTALL.md and that is what I used. I won't recommend it again.
> 
> I mixed up the issue opener with a commenter about WSL. (I guess I'm still a little new)

No worries!

**Comment by basilstr** [comment] 2020-12-21 16:29
Many thanks to RogierB.
I add to GemFile 
gem "thor", "~> 0.20.3"
Then I executed
bundle update thor
and this problem has been solved

**Comment by gravitystorm** [comment] 2021-01-20 18:22
I've investigated this today, and figured out what's going on. We have Thor 1.0.1 in our Gemfile.lock, and there's also the `ruby-thor` Ubuntu package that is version 0.19.4. Importantly, the `bundler` ubuntu package depends on the `ruby-thor` package, so if you use the packaged version of bundler and you run `bundle exec (something) you get the error. Bundler ends up loading both versions of thor - first from the package in order for bundler itself to work, then the gem version as part of loading all the gems in our Gemfile

The question then is why do we have the ubuntu packaged version of bundler installed? We have a specific line in the INSTALL instructions to install bundler using rubygems. Note that this approach - using gem instead of apt - was added 7 years ago for unrelated reasons. But more recently, [the instructions were updated](https://github.com/openstreetmap/openstreetmap-website/commit/9299f8ca23d7cd7a1cb2f080bf6bd440140d3637) to also install the `bundler` package. At the time this wouldn't have caused any problems, but after https://github.com/openstreetmap/openstreetmap-website/commit/aa7256d617748e94d1b6295debc58a14819f0eae there is a lurking problem with the Thor major version mismatch.

My suggestion would be to remove the ubuntu package `bundler` from the installation list, and revert to installing bundler only via the `gem install` approach. But I don't know why the package was added - @tomhughes can you remember?

But I'm aware that if a developer already has the Ubuntu `bundler` package installed for some other reason, things might go awry. Less likely on a fresh VM image, but more likely if they are developing normally. I'm not sure whether there's an approach that can fix it here. Constraining our Gemfile (as per the workaround described above) is only a temporary fix, because as soon as the `ruby-thor` package is updated to v1+ we will land right back here again. 

Personally I have avoided this on my own laptop by not having installed the packaged version of bundler.

Finally, this might be the root cause of the other complaints about 'yarn:install' recently, since it is the first thing in the INSTALL notes that uses `bundle exec`.

**Comment by tomhughes** [comment] 2021-01-21 16:46
So https://github.com/openstreetmap/openstreetmap-website/issues/2299#issuecomment-508174921 seems to be the origin of that install command being added.

**Comment by gravitystorm** [comment] 2021-01-21 17:00
> Bundler ends up loading both versions of thor

For what it's worth, I've also investigated the problems with the `ruby-bundler` package, to see why it breaks and other options (like installing bundler via gems, or on Fedora etc) work fine. The problem originates in the upstream Debian package, but I've no idea if/when it will be fixed since it touches on the concept of vendoring which is a sore point in many parts of that world. I've updated both the [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955405) and [Ubuntu](https://bugs.launchpad.net/ubuntu/+source/ruby-thor/+bug/1885424) bug trackers [with the root cause](https://github.com/erikhuda/thor/issues/721#issuecomment-606174523), but I don't think we should hold our breath.

**Comment by gravitystorm** [comment] 2021-01-21 17:03
> So [#2299 (comment)](https://github.com/openstreetmap/openstreetmap-website/issues/2299#issuecomment-508174921) seems to be the origin of that install command being added.

I didn't notice that at the time, but it looks like that OP missed the instruction to install bundler via the `gem install` route. Using the package would normally be entirely reasonable, and wouldn't have caused any problems back then anyway, since whatever caused our original `gem install` instruction was ancient history by that point, and the thor-vendoring problem wasn't revealed yet either.

**Comment by tomhughes** [comment] 2021-01-21 17:05
The interesting thing is that they haven't unbundled eveything - the `ruby-bundler` package does still have some vendored gems.

I just checked and the Fedora package doesn't unbundle thor.

**Closed** 2021-01-21 17:05 UTC
Labels: support
