### ISSUE TITLE
Space needed after URL in Notes resolution e-mail

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#2660] opened 2020-06-20 12:33 UTC
A space is needed after the URL here:

> More details about the note can be found at https://www.openstreetmap.org/note/262534.

Some mail systems include the dot in the URL. Mail pushed to Mailman, for instance, does this.

**Comment by tomhughes** [comment] 2020-06-20 13:44
You appear to have confused what you would like with what is required...

It's a fact of life that detection of URLs in plain text emails is naturally heuristic in nature and nothing we do will make it perfect so I don't see any reason to deliberate distort the grammar of messages in order to favour certain clients.

The correct solution is to include HTML versions of the message where the links can be accurately marked up, which we already do for this particular message, so this is only going to be a problem if you are deliberately preferring the plain text version.

I also don't really understand what mailman has to do with anything - that is a mailing list system so the display of the message is still a matter for the email client that eventually receives a message and is nothing to do with mailman. Or are you perhaps referring to sending the mail through a mailman list that has been configured to strip the HTML version of the message?

**Comment by gravitystorm** [comment] 2020-07-08 10:01
Duplicate of #1844

**Closed by gravitystorm** 2020-07-08 10:01 UTC
