### ISSUE TITLE
`code` tags produced by markdown in user content do not follow direction of surrounding text

### ISSUE THREAD

**Issue by bgo-eiu** [openstreetmap/openstreetmap-website#3762] opened 2022-10-21 20:46 UTC
### How to reproduce the issue?

This issue falls under the umbrella of #3427. This is related but different from the issue discussed in #3428 and for which a draft is posted at #3429.

When a user includes Markdown formatted to become `<code></code>` in a diary entry, this text is impacted by direction override styling which means that even with `dir="auto"` added to the overall diary content, the text will render only in the direction of the interface language, causing RTL characters to appear LTR in LTR interfaces and LTR characters to appear RTL in RTL interfaces. I think this might be coming from somewhere in Bootstrap, but I am not sure. In the CSS, this is the rule that needs to be removed from somewhere:

    pre, code, kbd, samp {
        direction: rtl /* presumably ltr in ltr layouts */
        unicode-bidi: bidi-override; /* this causes dir=auto to be ignored
    }
    
See for example in this recent diary entry:
https://www.openstreetmap.org/user/b-unicycling/diary/400151

### Screenshot(s) or anything else?

In the console here, I have applied corrections to the text alignment and direction of the overall diary entry, and the issue with `code` text is apparent:

![image](https://user-images.githubusercontent.com/100172442/197285762-da2a9e08-fbbe-4f8a-ae79-d8a71f6fe034.png)

This is after unchecking `unicode-bidi` in the console style panel:

![image](https://user-images.githubusercontent.com/100172442/197285852-46c8fa74-4d1a-43a7-b784-12a4be241d7e.png)

**Comment by AntonKhorev** [comment] 2023-12-26 02:47
#4104 was a duplicate of this, now fixed

**Closed** 2023-12-26 13:38 UTC
Labels: diaries
