### ISSUE TITLE
Add link to read changeset comment notifications

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2377] opened 2019-09-29 17:02 UTC
1. User gets notification that "XYZ has commented on one of your changesets"
2. User clicks the link and replies to the comment.
3. Days later, User wants to take a second look, but nowhere on the website is a list of such read notifications kept. He has no way to get back to that changeset other than sifting through his hundreds of changesets, hoping he remembers which one too.

**Comment by gravitystorm** [comment] 2019-09-29 17:10
See my comment at https://github.com/openstreetmap/openstreetmap-website/issues/2102#issuecomment-474798118

**Comment by aawiseman** [comment] 2021-04-23 23:25
I think this would be a big improvement.

**Comment by danieldegroot2** [comment] 2022-11-04 23:30
Duplicate of #1387

**Comment by mmd-osm** [comment] 2024-06-30 10:00
Closing as duplicate of #1387.

**Closed by mmd-osm** 2024-06-30 10:00 UTC
