### ISSUE TITLE
Notifications for changeset comments

### ISSUE THREAD

**Issue by 1T-money** [openstreetmap/openstreetmap-website#3468] opened 2022-02-23 00:18 UTC
### Description

I think it would be a good idea to get notifications for comments on your changesets on the website / iD editor (like there are with messages). It looks like this idea has been discussed years ago, but I think it's still relevant and would be very helpful. It would be easier than having to check emails.

**Comment by tomhughes** [comment] 2022-02-23 00:49
Why are you opening a duplicate of #3182?

You can't pretend you didn't know because you commented on it half an hour before opening this!

Please stop wasting our time.

**Closed by tomhughes** 2022-02-23 00:49 UTC
