### ISSUE TITLE
[API] Can not GET/DELETE a preference with a dot in its name. Ex: 

### ISSUE THREAD

**Issue by Binnette** [openstreetmap/openstreetmap-website#5004] opened 2024-07-19 12:32 UTC
### URL

https://api.openstreetmap.org/api/0.6/user/preferences/diary.default_language

### How to reproduce the issue?

1. List your preferences: `curl -X GET -H "Authorization: Bearer $Token" https://api.openstreetmap.org/api/0.6/user/preferences/ -w "\n%{http_code}\n"` 
````
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="OpenStreetMap server" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
  <preferences>
    <preference k="diary.default_language" v="en"/>
    <preference k="gps.trace.visibility" v="identifiable"/>
    <preference k="nbInvalid" v="-1"/>
    <preference k="nbValid" v="-1"/>
  </preferences>
</osm>

200
````
2. It works and return http status code 200
3. Get preference without dot in name: `curl -X GET -H "Authorization: Bearer $Token" https://api.openstreetmap.org/api/0.6/user/preferences/nbValid -w "\n%{http_code}\n"`
````
-1
200
````
4. It works and return -1 (nbValid value) and http status code 200
5. Get preference without dot in name: `curl -X GET -H "Authorization: Bearer $Token" https://api.openstreetmap.org/api/0.6/user/preferences/diary.default_language -w "\n%{http_code}\n"`
````

404
````
6. It does not work. Returns empty and 404

**Comment by mmd-osm** [comment] 2024-07-19 12:40
That's really a duplicate of #3787.

**Closed by mmd-osm** 2024-07-19 12:40 UTC
