### ISSUE TITLE
Application error opening note URL

### ISSUE THREAD

**Issue by joshas** [openstreetmap/openstreetmap-website#3811] opened 2022-11-19 18:09 UTC
### URL

https://www.openstreetmap.org/note/3420572

### How to reproduce the issue?

1. Open URL in web browser: https://www.openstreetmap.org/note/3420572

### Screenshot(s) or anything else?

Exact error message:

> Application error
> 
> The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

**Comment by mmd-osm** [comment] 2022-11-19 18:12
Probably a duplicate of #2146

**Comment by tomhughes** [comment] 2022-11-20 00:05
Indeed.

**Closed by tomhughes** 2022-11-20 00:05 UTC
