### ISSUE TITLE
User Api: 403 Forbidden when querying user information

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/openstreetmap-website#2086] opened 2018-12-12 22:26 UTC
While running the integration tests for osmapi, I noticed that now when querying the user information of another user with a logged in user (OAuth), the API always returns a ...
`Forbidden (403) - You have not permitted the application access to this facility`

As in #2085, this is independent of whether the OAuth token used has permission to everything or nothing (all checkboxes checked / no checkboxes checked).

Anonymously querying user information is still possible.

**Comment by tomhughes** [comment] 2018-12-12 22:35
Duplicate of #2085 (I realise that's not immediately obvious but #2083 will be the cause for both).

**Closed by tomhughes** 2018-12-12 22:35 UTC
