### ISSUE TITLE
When i refresh, auto redirect to login

### ISSUE THREAD

**Issue by sphr9999** [openstreetmap/openstreetmap-website#2665] opened 2020-06-24 08:14 UTC
When i build to deploy. I refresh, website auto logout, and redirect to login. Help me. Thanks

**Comment by gravitystorm** [comment] 2020-06-24 08:17
Hi @sphr9999 you will need to give us a lot more context about what you are trying to do. What rails environment you are in (development or production), what page you are viewing, steps to recreate the problem, and so on.

**Comment by sphr9999** [comment] 2020-06-24 08:59
Thank @gravitystorm for the feedback. 
I used Docker to deploy website to server.
<img width="930" alt="Screen Shot 2020-06-24 at 15 55 55" src="https://user-images.githubusercontent.com/31273626/85525324-319a3b00-b633-11ea-8130-b81828c3bff4.png">
when website was at edit page, with room >16 and loaded data. I refresh website, after website logout and redirect to login. I hope it redirect current page and not logout.

**Comment by sphr9999** [comment] 2020-06-24 09:08
I clone from source code from master branch and do not edit. I don't know I forgot any configuration at where. Sorry, i do not use English well. Please help me.

**Comment by sphr9999** [comment] 2020-06-25 03:42
help me, please

**Comment by gravitystorm** [comment] 2020-06-25 14:50
I'm afraid that I don't know the cause of the problem. My suggestions would be to check if the session store is working on your docker image (perhaps there is something related to having a read-only filesystem, that's the only guess I can make). You say that it happens on the edit page - is it only on that page? If other logged-in pages work fine, perhaps there is a problem with the iD setup.

More generally, we can only offer support for setting up a local development environment, for people who are planning to submit pull requests. We don't have enough volunteers to help debug production issues, or deployment setups like running the app within a container. 

I'm happy to leave this issue open for a few days to see if anyone else wants to make a guess, or if you want to provide further information (like an error log) that might help one of us make a better guess.

**Comment by gravitystorm** [comment] 2020-07-04 12:01
Closing, since there have been no updates or suggestions.

**Closed by gravitystorm** 2020-07-04 12:01 UTC
